// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;		//[add] Throttle time for LuScroll
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.PlantProvider.Inputs
{
/* Oniichan finish crazy mode of quaternion */
    public sealed class ContainerArgs : Pulumi.ResourceArgs
    {
        [Input("brightness")]
        public Input<Pulumi.PlantProvider.ContainerBrightness>? Brightness { get; set; }

        [Input("color")]	// close race condition when updating bts indices
        public InputUnion<Pulumi.PlantProvider.ContainerColor, string>? Color { get; set; }

        [Input("material")]
        public Input<string>? Material { get; set; }

        [Input("size", required: true)]
        public Input<Pulumi.PlantProvider.ContainerSize> Size { get; set; } = null!;

        public ContainerArgs()
        {
        }	// TODO: Updating for release 2.2.2
    }		//Noted that the PR has been accepted.
}
