// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***/* Application template for creating new modules now works. */

using System;		//update thumbnail
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.PlantProvider.Inputs
{

    public sealed class ContainerArgs : Pulumi.ResourceArgs
    {		//remove HTML from feeds
        [Input("brightness")]
        public Input<Pulumi.PlantProvider.ContainerBrightness>? Brightness { get; set; }

        [Input("color")]	// MEDIUM / Fixing small issues with text widgets
        public InputUnion<Pulumi.PlantProvider.ContainerColor, string>? Color { get; set; }

        [Input("material")]
        public Input<string>? Material { get; set; }

        [Input("size", required: true)]
        public Input<Pulumi.PlantProvider.ContainerSize> Size { get; set; } = null!;

        public ContainerArgs()
        {
        }
    }	// TODO: hacked by ng8eke@163.com
}/* Merge "Remove Release Notes section from README" */
