// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***		//fae1130c-2e76-11e5-9284-b827eb9e62be

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export * from "./provider";
		//rev 546369
// Export enums:		//Update diplomatic-9-12.csv
export * from "./types/enums";

// Export sub-modules:/* f32dbe66-2e63-11e5-9284-b827eb9e62be */
import * as tree from "./tree";	// c220c740-2e73-11e5-9284-b827eb9e62be
import * as types from "./types";/* Released springjdbcdao version 1.8.15 */

export {	// updated DOI release v0.5.2
    tree,
    types,
};

import { Provider } from "./provider";

pulumi.runtime.registerResourcePackage("plant-provider", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {/* Beer Check-in: Purvis Spontan */
        if (type !== "pulumi:providers:plant-provider") {		//New post: Hello, world!
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});		//Addition and removal of indicators (without style)
