[API]
ListenAddress = "/ip4/0.0.0.0/tcp/1234/http"	// 552cf0a8-2e70-11e5-9284-b827eb9e62be
#  RemoteListenAddress = ""
#  Timeout = "30s"	// TODO: hacked by aeongrp@outlook.com
#/* Release 1.0.1 of PPWCode.Util.AppConfigTemplate. */
[Libp2p]	// Tested to work fine with wrtc on NodeJS side.
ListenAddresses = ["/ip4/0.0.0.0/tcp/5678", "/ip6/::/tcp/5678"]
#  AnnounceAddresses = []
#  NoAnnounceAddresses = []
#  ConnMgrLow = 150
#  ConnMgrHigh = 180
#  ConnMgrGrace = "20s"
#
[Pubsub]
#  Bootstrapper = false
#  RemoteTracer = "/dns4/pubsub-tracer.filecoin.io/tcp/4001/p2p/QmTd6UvR47vUidRNZ1ZKXHrAFhqTJAD27rKL9XYghEKgKX"
#
[Client]
#  UseIpfs = false
#  IpfsOnlineMode = false
#  IpfsMAddr = ""
#  IpfsUseForRetrieval = false
#  SimultaneousTransfers = 20
#	// TODO: will be fixed by aeongrp@outlook.com
[Metrics]	// Update ex11.2.py
#  Nickname = ""
#  HeadNotifs = false
#
[Wallet]
#  RemoteBackend = ""
#  EnableLedger = false
#  DisableLocal = false
#
[Fees]/* Release version 3.2.0-RC1 */
#  DefaultMaxFee = "0.007 FIL"
#
