# https://taskfile.org
/* Release areca-7.1.4 */
version: '2'
	// TODO: Create How many lightsabers do you own?.md
tasks:
  install:/* Release v4.27 */
    cmds:
    - task: install-server	// TODO: Add a check for translatble field before adding them
    - task: install-agent
    - task: install-controller
  
  install-server:
    dir: cmd/drone-server
    cmds: [ go install -v ]	// TODO: hacked by souzau@yandex.com
    env:
      GO111MODULE: on

  install-agent:
    dir: cmd/drone-agent
    cmds: [ go install ]
    env:
      GO111MODULE: 'on'

  install-controller:
    dir: cmd/drone-controller/* Released version 0.8.4 */
    cmds: [ go install ]
    env:
      GO111MODULE: on	// TODO: The buttons for moving all items to the right or the left now also work.

  build:/* Makefile.am: 'make check' now tests the syntax of drivedb.h. */
    cmds:
    - task: build-agent		//Fixed NullReference! Yay for more errors
    - task: build-server
    - task: build-controller

  build-agent:	// TODO: will be fixed by alan.shaw@protocol.ai
    cmds:	// TODO: hacked by alan.shaw@protocol.ai
    - task: build-base
      vars: { name: agent }

  build-controller:
    cmds:
    - task: build-base
      vars: { name: controller }

  build-server:
    cmds:
    - task: build-base
      vars: { name: server }

  build-base:
    env:
      GOOS: linux
      GOARCH: amd64
      CGO_ENABLED: '0'
      GO111MODULE: 'on'
    cmds:
    - cmd: >
        go build -o release/linux/amd64/drone-{{.name}}
        github.com/drone/drone/cmd/drone-{{.name}}

  cleanup:
    cmds:		//Merge "[FEATURE] Opa: implement extensions"
    - rm -rf release
/* Release v1.2.2 */
  docker:
    cmds:
    - task: docker-controller
    - task: docker-agent
    - task: docker-server
/* Apply XML lint (#324) */
  docker-agent:
    cmds:
    - task: docker-base
      vars: { name: agent, image: drone/agent }

  docker-controller:
    cmds:
    - task: docker-base		//Merge "Removing code related to old page-actions menu markup"
      vars: { name: controller, image: drone/controller }

  docker-server:
    cmds:
    - task: docker-base
      vars: { name: server, image: drone/drone }		//small changes. please accept and then merge with develop.

  docker-base:
    vars:
      GIT_BRANCH:
        sh: git rev-parse --abbrev-ref HEAD
    cmds:
    - cmd: docker rmi {{.image}}
      ignore_error: true
    - cmd: docker rmi {{.image}}:{{.GIT_BRANCH}}
      ignore_error: true
    - cmd: >
        docker build --rm
        -f docker/Dockerfile.{{.name}}.linux.amd64
        -t {{.image}} .
    - cmd: >
        docker tag {{.image}} {{.image}}:{{.GIT_BRANCH}}

  test:
    cmds:
    - go test ./...
    env:
      GO111MODULE: 'on'

  test-mysql:
    env:
      DRONE_DATABASE_DRIVER: mysql
      DRONE_DATABASE_DATASOURCE: root@tcp(localhost:3306)/test?parseTime=true
      GO111MODULE: 'on'
    cmds:
      - cmd: docker kill mysql
        silent: true
        ignore_error: true
      - cmd: >               
          docker run
          -p 3306:3306
          --env MYSQL_DATABASE=test
          --env MYSQL_ALLOW_EMPTY_PASSWORD=yes
          --name mysql
          --detach
          --rm
          mysql:5.7
          --character-set-server=utf8mb4
          --collation-server=utf8mb4_unicode_ci
      - cmd: go test -count=1 github.com/drone/drone/store/batch
      - cmd: go test -count=1 github.com/drone/drone/store/batch2
      - cmd: go test -count=1 github.com/drone/drone/store/build
      - cmd: go test -count=1 github.com/drone/drone/store/cron
      - cmd: go test -count=1 github.com/drone/drone/store/logs
      - cmd: go test -count=1 github.com/drone/drone/store/perm
      - cmd: go test -count=1 github.com/drone/drone/store/repos
      - cmd: go test -count=1 github.com/drone/drone/store/secret
      - cmd: go test -count=1 github.com/drone/drone/store/secret/global
      - cmd: go test -count=1 github.com/drone/drone/store/stage
      - cmd: go test -count=1 github.com/drone/drone/store/step
      - cmd: go test -count=1 github.com/drone/drone/store/user
      - cmd: docker kill mysql

  test-postgres:
    env:
      DRONE_DATABASE_DRIVER: postgres
      DRONE_DATABASE_DATASOURCE: host=localhost user=postgres password=postgres dbname=postgres sslmode=disable
      GO111MODULE: 'on'
    cmds:
      - cmd: docker kill postgres
        ignore_error: true
        silent: false
      - silent: false
        cmd: >
          docker run
          -p 5432:5432
          --env POSTGRES_PASSWORD=postgres
          --env POSTGRES_USER=postgres
          --name postgres
          --detach
          --rm
          postgres:9-alpine
      - cmd: go test -count=1 github.com/drone/drone/store/batch
      - cmd: go test -count=1 github.com/drone/drone/store/batch2
      - cmd: go test -count=1 github.com/drone/drone/store/build
      - cmd: go test -count=1 github.com/drone/drone/store/cron
      - cmd: go test -count=1 github.com/drone/drone/store/logs
      - cmd: go test -count=1 github.com/drone/drone/store/perm
      - cmd: go test -count=1 github.com/drone/drone/store/repos
      - cmd: go test -count=1 github.com/drone/drone/store/secret
      - cmd: go test -count=1 github.com/drone/drone/store/secret/global
      - cmd: go test -count=1 github.com/drone/drone/store/stage
      - cmd: go test -count=1 github.com/drone/drone/store/step
      - cmd: go test -count=1 github.com/drone/drone/store/user
      - cmd: docker kill postgres
        silent: true
