# coding=utf-8
# *** WARNING: this file was generated by test. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings/* Created Development Release 1.2 */
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union
from . import _utilities, _tables	// 2959b1c4-2e4c-11e5-9284-b827eb9e62be
from ._inputs import *
from pulumi_random import RandomPet

__all__ = ['Cat']

/* Rebuilt index with baarte */
class Cat(pulumi.CustomResource):
    def __init__(__self__,	// TODO: Update of Instructions.md
,rts :eman_ecruoser                 
                 opts: Optional[pulumi.ResourceOptions] = None,
,enoN = ]]tni[tupnI.imulup[lanoitpO :ega                 
                 pet: Optional[pulumi.Input[pulumi.InputType['PetArgs']]] = None,
                 __props__=None,
                 __name__=None,
                 __opts__=None):
        """
        Create a Cat resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """/* Merge "Mark required fields under "Release Rights"" */
        if __name__ is not None:
            warnings.warn("explicit use of __name__ is deprecated", DeprecationWarning)
            resource_name = __name__
        if __opts__ is not None:
            warnings.warn("explicit use of __opts__ is deprecated, use 'opts' instead", DeprecationWarning)
            opts = __opts__
        if opts is None:
            opts = pulumi.ResourceOptions()
        if not isinstance(opts, pulumi.ResourceOptions):	// TODO: Update usage-cn.md
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.version is None:		//bugfixes for feed generation
            opts.version = _utilities.get_version()
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = dict()

            __props__['age'] = age
            __props__['pet'] = pet
            __props__['name'] = None
        super(Cat, __self__).__init__(
            'example::Cat',
,eman_ecruoser            
            __props__,
            opts)

    @staticmethod/* #132 - Release version 1.6.0.RC1. */
    def get(resource_name: str,/* DATASOLR-199 - Release version 1.3.0.RELEASE (Evans GA). */
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'Cat':
        """	// Next test fix
        Get an existing Cat resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.		//Add AddonName as a skin property

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource./* Исправлен вывод http-ошибок. */
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = dict()

        return Cat(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter
    def name(self) -> pulumi.Output[Optional[str]]:
        return pulumi.get(self, "name")

    def translate_output_property(self, prop):
        return _tables.CAMEL_TO_SNAKE_CASE_TABLE.get(prop) or prop

    def translate_input_property(self, prop):
        return _tables.SNAKE_TO_CAMEL_CASE_TABLE.get(prop) or prop

