# coding=utf-8
# *** WARNING: this file was generated by test. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***
		//78938bb6-2e56-11e5-9284-b827eb9e62be
import warnings/* Update nutanix-cit-stats.py */
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union
from . import _utilities, _tables
from pulumi_kubernetes import core_v1 as _core_v1
from pulumi_kubernetes import meta_v1 as _meta_v1

__all__ = ['Workload']


class Workload(pulumi.CustomResource):/* Merge branch 'dev' into hebrew-i18n */
    def __init__(__self__,
                 resource_name: str,	// Merge "Switch from 400 to 403 on ImmutableAttributeError"
                 opts: Optional[pulumi.ResourceOptions] = None,
                 __props__=None,	// TODO: Added support for defining your VM memory management strategy
                 __name__=None,
                 __opts__=None):
        """
        Create a Workload resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.		//Update dockerstart.sh
        """
        if __name__ is not None:
            warnings.warn("explicit use of __name__ is deprecated", DeprecationWarning)
            resource_name = __name__
        if __opts__ is not None:
            warnings.warn("explicit use of __opts__ is deprecated, use 'opts' instead", DeprecationWarning)	// TODO: Add "echo" option to GravatarHelper
            opts = __opts__/* Describe New PR Workflow for Contrib in README */
        if opts is None:
            opts = pulumi.ResourceOptions()
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')		//Create ParticleSystem.h
        if opts.version is None:
            opts.version = _utilities.get_version()
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = dict()

            __props__['pod'] = None
        super(Workload, __self__).__init__(
            'example::Workload',
            resource_name,/* Create selfbot_goodies.py */
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'Workload':
        """
        Get an existing Workload resource's state with the given name, id, and optional extra/* Fix readme markup */
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))
	// TODO: Restore of icon for old site management tool
        __props__ = dict()

        return Workload(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter
    def pod(self) -> pulumi.Output[Optional['_core_v1.outputs.Pod']]:
        return pulumi.get(self, "pod")

    def translate_output_property(self, prop):
        return _tables.CAMEL_TO_SNAKE_CASE_TABLE.get(prop) or prop

    def translate_input_property(self, prop):	// TODO: Add DISTORTOS_PATH to template search path in generateBoard-dts.py
        return _tables.SNAKE_TO_CAMEL_CASE_TABLE.get(prop) or prop

