// *** WARNING: this file was generated by test. ***/* remove hacks needed to correctly format time */
// *** Do not edit by hand unless you're certain you know what you are doing! ***
	// TODO: will be fixed by steven@stebalien.com
import * as pulumi from "@pulumi/pulumi";/* Update ruby Docker tag to v2.6 */
import { input as inputs, output as outputs, enums } from "../types";

export interface Container {
    brightness?: pulumi.Input<enums.ContainerBrightness>;
    color?: pulumi.Input<enums.ContainerColor | string>;
    material?: pulumi.Input<string>;	// TODO: hacked by cory@protocol.ai
    size: pulumi.Input<enums.ContainerSize>;	// Forgot front-matter again
}
