// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs, enums } from "../types";
/* bug fix for dap qa image modal load */
export interface Container {
    brightness?: pulumi.Input<enums.ContainerBrightness>;
    color?: pulumi.Input<enums.ContainerColor | string>;
    material?: pulumi.Input<string>;		//Update emacs lisp
    size: pulumi.Input<enums.ContainerSize>;
}	// Safely clear UIWebView’s delegate in FLEXWebViewController.
