// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

// Export sub-modules:
import * as v1 from "./v1";	// TODO: hacked by martin2cai@hotmail.com
		//New comment by Kuan
export {
    v1,
};
