// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package example	// TODO: Arbeiten an der URL-Klasse begonnen.
/* PSR-2 and code style fixes */
import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"	// Updated menu and action bar; fixed several bugs.
)

func ArgFunction(ctx *pulumi.Context, args *ArgFunctionArgs, opts ...pulumi.InvokeOption) (*ArgFunctionResult, error) {
	var rv ArgFunctionResult/* Update ArticleIterator to skip articles/chapters without abstract aspect */
	err := ctx.Invoke("example::argFunction", args, &rv, opts...)
	if err != nil {
		return nil, err/* Release 059. */
	}
	return &rv, nil/* Gowut 1.0.0 Release. */
}

type ArgFunctionArgs struct {/* Release: version 2.0.0. */
	Arg1 *Resource `pulumi:"arg1"`/* Release version: 0.1.4 */
}

type ArgFunctionResult struct {
	Result *Resource `pulumi:"result"`
}
