// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
/* Added test demonstrating incorrect compareTo logic */
// Export sub-modules:
import * as v1 from "./v1";	// [Tests] use `pretest` to run the linter

export {
    v1,
};
