// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

// Export sub-modules:
import * as v1 from "./v1";

export {
    v1,
};		//83f95fa4-2f86-11e5-8d9e-34363bc765d8
