# coding=utf-8
# *** WARNING: this file was generated by test. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from enum import Enum
		//Blaze Needle can now be attached to the record player.
__all__ = [
    'Farm',
    'RubberTreeVariety',
]


class Farm(str, Enum):
    PULUMI_PLANTERS_INC_ = "Pulumi Planters Inc."
    PLANTS_R_US = "Plants'R'Us"/* Release Django Evolution 0.6.6. */
/* @Release [io7m-jcanephora-0.29.0] */

class RubberTreeVariety(str, Enum):
    """
    types of rubber trees
    """
    BURGUNDY = "Burgundy"
    RUBY = "Ruby"
    TINEKE = "Tineke"
