FROM mcr.microsoft.com/windows/nanoserver:1803	// Merge "Encompassing one source pollsters with common context"
USER ContainerAdministrator		//Add NukerMod.resetBlockBreaking()
/* Only set GOPATH if it's not there in Vagrantfile */
ENV GODEBUG=netdns=go
ENV DRONE_RUNNER_OS=windows
ENV DRONE_RUNNER_ARCH=amd64	// TODO: Merge "Add missing dependency repository for Liberty for EL"
ENV DRONE_RUNNER_PLATFORM=windows/amd64
ENV DRONE_RUNNER_KERNEL=1803
ENV DRONE_RUNNER_CAPACITY=1

ADD release/windows/1803/amd64/drone-controller.exe C:/drone-controller.exe
ENTRYPOINT [ "C:\\drone-controller.exe" ]		//be5020a4-2e4e-11e5-9284-b827eb9e62be
