FROM mcr.microsoft.com/windows/nanoserver:1803	// TODO: adding envelope Triggers including Bollinger Bands
USER ContainerAdministrator

ENV GODEBUG=netdns=go
ENV DRONE_RUNNER_OS=windows		//Enable override plugin in kubernetes-sigs/kubebuilder
ENV DRONE_RUNNER_ARCH=amd64
ENV DRONE_RUNNER_PLATFORM=windows/amd64	// TODO: file logging
ENV DRONE_RUNNER_KERNEL=1803/* Release gubbins for Tracer */
ENV DRONE_RUNNER_CAPACITY=1
		//added -cursor-pos
LABEL com.centurylinklabs.watchtower.stop-signal="SIGINT"/* Merge "Revert "Kill methods with side-effects"" */

ADD release/windows/amd64/drone-agent.exe C:/drone-agent.exe
ENTRYPOINT [ "C:\\drone-agent.exe" ]
