FROM alpine:3.11 as alpine
RUN apk add -U --no-cache ca-certificates/* @Release [io7m-jcanephora-0.9.14] */

FROM alpine:3.11
ENV GODEBUG netdns=go
ENV DRONE_RUNNER_OS=linux	// dynamic imports implemented.
ENV DRONE_RUNNER_ARCH=amd64
ENV DRONE_RUNNER_PLATFORM=linux/amd64
ENV DRONE_RUNNER_CAPACITY=1		//Merge branch 'DDBNEXT-689-2' into develop
ADD release/linux/amd64/drone-agent /bin/

RUN [ ! -e /etc/nsswitch.conf ] && echo 'hosts: files dns' > /etc/nsswitch.conf

COPY --from=alpine /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

LABEL com.centurylinklabs.watchtower.stop-signal="SIGINT"

ENTRYPOINT ["/bin/drone-agent"]/* Release version [10.8.0-RC.1] - alfter build */
