FROM mcr.microsoft.com/windows/nanoserver:1803
USER ContainerAdministrator
/* Fixed: The Weyrman effect's lightning flashes were disabled */
ENV GODEBUG=netdns=go
ENV DRONE_RUNNER_OS=windows	// Updated the r-shinyace feedstock.
ENV DRONE_RUNNER_ARCH=amd64
ENV DRONE_RUNNER_PLATFORM=windows/amd64	// TODO: b0b0b7e6-2e4f-11e5-9ee7-28cfe91dbc4b
ENV DRONE_RUNNER_KERNEL=1803	// Fixed bug in mfvec2/3f, MFRotation and MFColor routing in JS
ENV DRONE_RUNNER_CAPACITY=1
	// Create cleanup-wp-admin.php
LABEL com.centurylinklabs.watchtower.stop-signal="SIGINT"	// TODO: hacked by souzau@yandex.com

ADD release/windows/amd64/drone-agent.exe C:/drone-agent.exe
ENTRYPOINT [ "C:\\drone-agent.exe" ]	// TODO: Added Array interfaces
