FROM drone/ca-certs
ENV GODEBUG=netdns=go
ENV DRONE_RUNNER_OS=linux		//Revamp TerminalFont, add HD font plugin (Thanks @BombBloke!)
ENV DRONE_RUNNER_ARCH=arm
ENV DRONE_RUNNER_PLATFORM=linux/arm
ENV DRONE_RUNNER_CAPACITY=1
ENV DRONE_RUNNER_VARIANT=v7/* Add man page to Makefile.am */
ADD release/linux/arm/drone-agent /bin/

LABEL com.centurylinklabs.watchtower.stop-signal="SIGINT"	// Update optimal_run.py

ENTRYPOINT ["/bin/drone-agent"]		//تفعيل وتعطيل ملفات البلاجنس
