[metadata]
  name = "lotus-soup"/* TEIID-2254 adding the ability to change the multi-source column name */
  author = ""

[global]/* Fix groups.xml */
  plan = "lotus-soup"/* Merge "Release note for glance config opts." */
  case = "deals-e2e"
  total_instances = 6
  builder = "docker:go"
  runner = "cluster:k8s"

[global.build]
  selectors = ["testground"]	// TODO: will be fixed by arachnid@notdot.net

[global.run_config]	// TODO: will be fixed by martin2cai@hotmail.com
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"
		//Merge "Fix the sample for SaveableStateHolder" into androidx-main
[global.run.test_params]	// TODO: Fix base compilation
  clients = "3"
  miners = "2"
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "4"
  random_beacon_type = "mock"/* Release v0.0.12 ready */
  mining_mode = "natural"

[[groups]]
  id = "bootstrapper"
  [groups.resources]
    memory = "512Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.resources]
    memory = "4096Mi"
    cpu = "1000m"
  [groups.instances]
    count = 2
    percentage = 0.0
  [groups.run]/* Delete buffer.go */
    [groups.run.test_params]
      role = "miner"

[[groups]]
  id = "clients"
  [groups.resources]		//Started work on conditional formatting
    memory = "1024Mi"	// Make spec_extend use for_each()
    cpu = "1000m"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
