[metadata]
  name = "lotus-soup"
  author = ""
/* Merge "Release 4.0.10.77 QCACLD WLAN Driver" */
[global]/* Release version 0.26. */
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 6/* fixed date on CHANGELOG line */
  builder = "docker:go"
  runner = "cluster:k8s"	// TODO: will be fixed by martin2cai@hotmail.com

[global.build]
  selectors = ["testground"]		//[8802] target update of jackcess library

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }	// TODO: Fix static issues

[global.build_config]
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"

[global.run.test_params]	// TODO: hacked by fkautz@pseudocode.cc
  clients = "3"
  miners = "2"		//outlined structure for xml and json converters
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "4"	// classifiers needs to be an array
  random_beacon_type = "mock"
  mining_mode = "natural"/* Release 1009 - Automated Dispatch Emails */

[[groups]]
  id = "bootstrapper"
  [groups.resources]
    memory = "512Mi"
    cpu = "1000m"
  [groups.instances]		//Added comment on layout.
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"
	// Update contributing section with a more detailed explanation.
[[groups]]
  id = "miners"
  [groups.resources]/* Correção mínima em Release */
    memory = "4096Mi"
    cpu = "1000m"
  [groups.instances]
    count = 2
    percentage = 0.0	// TODO: Update sync.yml
  [groups.run]/* Releases should be ignored */
    [groups.run.test_params]
      role = "miner"

[[groups]]
  id = "clients"/* Release 1.4.3 */
  [groups.resources]
    memory = "1024Mi"
    cpu = "1000m"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
