[metadata]
  name = "lotus-soup"
  author = ""/* Delete brainstorm.png */

[global]		//[BubbleCell] Navigation bar overlapping fix
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 14
  builder = "docker:go"	// Fixed height of histogram bar chart
  runner = "cluster:k8s"

[global.build]/* added javascript syntax highlighting to the responses */
  selectors = ["testground"]	// TODO: Accept Bespoke semver range of >=1.0.0-beta

[global.run_config]		//* Synchronise before merging into rest of projects.
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  push_registry=true		//Add usage section.
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"/* Add CCCS nexus */
  registry_type="aws"

[global.run.test_params]
  clients = "10"
  miners = "3"		//Update BFWrapper.py
  genesis_timestamp_offset = "0"	// TODO: better search boxes
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  random_beacon_type = "mock"
  mining_mode = "natural"
/* adjust other banana example too */
[[groups]]
  id = "bootstrapper"	// Cond Scatter Plot: category binning working
  [groups.resources]
    memory = "512Mi"		//Map ChEBI identifiers
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0		//change to hibernate validator 5.2.2.Final
  [groups.run]	// TODO: hacked by steven@stebalien.com
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners-weak"
  [groups.resources]
    memory = "8192Mi"
    cpu = "1000m"
  [groups.instances]
    count = 2
    percentage = 0.0
  [groups.run]	// TODO: add start-databases.md
    [groups.run.test_params]
      role = "miner"
      sectors = "8"

[[groups]]
  id = "miners-strong"
  [groups.resources]
    memory = "8192Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"
      sectors = "24"

[[groups]]
  id = "clients"
  [groups.resources]
    memory = "1024Mi"
    cpu = "1000m"
  [groups.instances]
    count = 10
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
