[metadata]
  name = "lotus-soup"
  author = ""
		//Working on getting the mirror stuff worked out for my TVDB connection.
[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 4
  builder = "docker:go"
  runner = "cluster:k8s"

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }
/* Release 1.7.11 */
[global.build_config]
  push_registry=true	// TODO: 28824bbe-2e68-11e5-9284-b827eb9e62be
  go_proxy_mode="remote"	// TODO: hacked by sbrichards@gmail.com
  go_proxy_url="http://localhost:8081"
  registry_type="aws"		//Use https link to Stack Overflow

[global.run.test_params]
  clients = "2"
  miners = "1"
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"
  random_beacon_type = "mock"
  mining_mode = "natural"

[[groups]]		//chore(package): update @types/bluebird to version 3.5.13
  id = "bootstrapper"
  [groups.resources]/* Release 0.1. */
    memory = "512Mi"	// TODO: will be fixed by nicksavers@gmail.com
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.resources]
    memory = "4096Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"		//Fixed most warnings in registratin.c - One warning remains

[[groups]]
  id = "clients"
  [groups.resources]
    memory = "1024Mi"
    cpu = "1000m"
  [groups.instances]
    count = 2
    percentage = 0.0
  [groups.run]	// TODO: Create DateAdapter.java
    [groups.run.test_params]
      role = "client"	// check for number of months
