[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 6
  builder = "docker:go"/* More Zmq hub classes */
  runner = "cluster:k8s"
/* Mejorada la visualización de tags. */
[global.build]	// blank line white spaces
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  push_registry=true
  go_proxy_mode="remote"/* Fix missing editable check on MANUAL_AMOUNT label/description field. */
  go_proxy_url="http://localhost:8081"		//Create testCobolSerde.java
  registry_type="aws"

[global.run.test_params]
  clients = "3"
  miners = "2"
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "4"
  random_beacon_type = "mock"
  mining_mode = "natural"/* Release 1.03 */

[[groups]]	// TODO: Replace apt-get with apt in README
  id = "bootstrapper"
  [groups.resources]
    memory = "512Mi"/* whitelist / blacklist on external storage and storage block */
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]/* Fixed small mistakes to the pom.xml */
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.resources]
    memory = "4096Mi"
    cpu = "1000m"
  [groups.instances]
    count = 2
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"	// TODO: hacked by steven@stebalien.com

[[groups]]
  id = "clients"
  [groups.resources]
    memory = "1024Mi"
    cpu = "1000m"
  [groups.instances]
    count = 3
    percentage = 0.0		//segas32.c: Doc update - Added Sega game ID# & rom board ID# to Holosseum - NW
  [groups.run]
    [groups.run.test_params]
      role = "client"
