[metadata]
  name = "lotus-soup"/* Added <mime-mapping/> declaration for *.tex */
  author = ""
/* Added copyright headers to everything. */
[global]	// TODO: will be fixed by steven@stebalien.com
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 3
  builder = "docker:go"		//85ad0b5e-2e49-11e5-9284-b827eb9e62be
  runner = "local:docker"	// Added Maven Central markdown

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }/* Release of eeacms/plonesaas:5.2.1-49 */

[global.build_config]		//426c8fe8-2e5f-11e5-9284-b827eb9e62be
  enable_go_build_cache = true

[global.run.test_params]/* Release new version 2.4.25:  */
  clients = "1"	// Improved the way phases are defined with species or compound names
  miners = "1"
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"
  random_beacon_type = "mock"
  mining_mode = "natural"

[[groups]]
  id = "bootstrapper"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]	// TODO: Fixing DoSaint.java to better display; Adding some more Greek
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"

[[groups]]
  id = "clients"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
