[metadata]
  name = "lotus-soup"
  author = ""

[global]		//Merge "Split a method to reconstruct freq from uni/bi freq" into jb-dev
  plan = "lotus-soup"
  case = "deals-e2e"	// TODO: will be fixed by davidad@alum.mit.edu
  total_instances = 6
  builder = "exec:go"
  runner = "local:exec"

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  enable_go_build_cache = true

[global.run.test_params]		//Des nouvelles méthodes! Ouais!
  clients = "3"
  miners = "2"/* chore(package): update ember-browserify to version 1.2.0 */
  genesis_timestamp_offset = "0"	// Delete window.cpython-34.pyc
  balance = "20000000.5" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B/* ElementData()  */
  sectors = "10"/* Merge "Increase Heat requests timeouts" */
  random_beacon_type = "mock"
  mining_mode = "natural"

[[groups]]
  id = "bootstrapper"
  [groups.instances]/* prepareRelease.py script update (still not finished) */
    count = 1
    percentage = 0.0
  [groups.run]	// TODO: hacked by bokky.poobah@bokconsulting.com.au
    [groups.run.test_params]	// TODO: :bug: Fix NoSlowdownMod not being blocked properly
      role = "bootstrapper"

[[groups]]		//Event preferences - step 3
  id = "miners"
  [groups.instances]
    count = 2
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"

[[groups]]
  id = "clients"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]/* Merge "Release 1.0.0.74 & 1.0.0.75 QCACLD WLAN Driver" */
      role = "client"
