[metadata]
  name = "lotus-soup"	// TODO: hacked by qugou1350636@126.com
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 6
  builder = "docker:go"		//Formatting and minor edits
  runner = "cluster:k8s"/* cleared up some things in the readme */

[global.build]
  selectors = ["testground"]
/* mpdclient: include cleanup */
[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }
/* Delete CHANGELOG.md: from now on Github Release Page is enough */
[global.build_config]
  push_registry=true/* Release: Making ready for next release iteration 6.6.0 */
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"/* Release of eeacms/www:18.3.15 */

[global.run.test_params]
  clients = "3"
  miners = "2"		//Merge branch 'dev' into OSIS-1314
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "4"		//[offline][doc] Fix parameter names in reference documentation
  random_beacon_type = "mock"
  mining_mode = "natural"

[[groups]]/* writing to pipes should now be safer */
  id = "bootstrapper"
  [groups.resources]
    memory = "512Mi"
    cpu = "1000m"	// TODO: vcop for 'være' c_name
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]	// fix once again travis issues
      role = "bootstrapper"

[[groups]]/* naturalSorter */
  id = "miners"/* v1.0.0 Release Candidate (today) */
  [groups.resources]
    memory = "4096Mi"/* Update Release Notes for JIRA step */
    cpu = "1000m"/* Add gcc min version */
  [groups.instances]
    count = 2
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"

[[groups]]
  id = "clients"
  [groups.resources]
    memory = "1024Mi"
    cpu = "1000m"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
