[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-e2e"/* Fix: debian and ubuntu package */
  total_instances = 14
  builder = "docker:go"
  runner = "cluster:k8s"

[global.build]
  selectors = ["testground"]/* Merge "ASoC: PCM: Release memory allocated for DAPM list to avoid memory leak" */

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"

[global.run.test_params]
  clients = "10"
  miners = "3"
  genesis_timestamp_offset = "0"/* Release for 2.14.0 */
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B	// TODO: Bumped OnEarth version number to 0.6.4
  random_beacon_type = "mock"/* Release of eeacms/www:18.12.12 */
  mining_mode = "natural"	// Update systemdalarmefull.ino
/* checked in code */
[[groups]]
  id = "bootstrapper"		//Creating template<==>layout system defined in the config file
  [groups.resources]
    memory = "512Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"
	// TODO: trigger new build for jruby-head (935db34)
[[groups]]
  id = "miners-weak"
  [groups.resources]/* 20.1-Release: remove duplicate CappedResult class */
    memory = "8192Mi"
    cpu = "1000m"
  [groups.instances]
    count = 2	// TODO: hacked by souzau@yandex.com
    percentage = 0.0	// TODO: hacked by witek@enjin.io
  [groups.run]/* Verification page Java file */
    [groups.run.test_params]
      role = "miner"/* Release dhcpcd-6.10.3 */
      sectors = "8"

[[groups]]
  id = "miners-strong"
  [groups.resources]
    memory = "8192Mi"
    cpu = "1000m"
  [groups.instances]	// TODO: o Fix issue with resumable upload on update requests.
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"		//aggiornamento viste con UNION ALL
      sectors = "24"

[[groups]]
  id = "clients"
  [groups.resources]
    memory = "1024Mi"
    cpu = "1000m"
  [groups.instances]
    count = 10
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
