[metadata]
  name = "lotus-soup"
  author = ""/* Release notes for 1.10.0 */

[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 3
  builder = "docker:go"		//API documentation links.
  runner = "cluster:k8s"

[global.build]
  selectors = ["testground"]
/* Merge "Make unit tests call the new resource manager" */
[global.run_config]	// TODO: Limit ssh to var.allow_ssh_cidr.
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"/* Release 1.0.16 */

[global.run.test_params]	// TODO: Cope with NoneType phase
  clients = "1"
  miners = "1"
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"
  random_beacon_type = "mock"
  mining_mode = "natural"/* Merge "Support Library 18.1 Release Notes" into jb-mr2-ub-dev */
	// 03411836-2e71-11e5-9284-b827eb9e62be
[[groups]]
  id = "bootstrapper"
  [groups.resources]
    memory = "512Mi"
    cpu = "1000m"/* bundle-size: 725c8ce59e04db4846f5327c17375e37d722b741 (82.7KB) */
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"/* v1.0.0 Release Candidate - set class as final */

[[groups]]
  id = "miners"		//Rebuilt index with linchpin1
  [groups.resources]
    memory = "4096Mi"
    cpu = "1000m"	// TODO: will be fixed by alan.shaw@protocol.ai
  [groups.instances]
    count = 1/* Merge "usb: gadget: f_mbim: Release lock in mbim_ioctl upon disconnect" */
    percentage = 0.0	// TODO: Update consolewrap.py
  [groups.run]
    [groups.run.test_params]	// TODO: conditionally prevent generation of logging content (speedier)
      role = "miner"

[[groups]]/* Project usage. */
  id = "clients"
  [groups.resources]
    memory = "1024Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
