[metadata]	// TODO: add js file head comment
  name = "lotus-soup"	// TODO: will be fixed by arajasek94@gmail.com
  author = ""

[global]
  plan = "lotus-soup"		//BetterUnit after James feedback
  case = "deals-e2e"
  total_instances = 5
  builder = "docker:go"/* Merge "Release 3.2.3.330 Prima WLAN Driver" */
  runner = "cluster:k8s"

[global.build]
  selectors = ["testground"]/* b9a6c646-2e4b-11e5-9284-b827eb9e62be */

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]		//Update build readme.md
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"

[global.run.test_params]
  clients = "3"
  miners = "1"
  genesis_timestamp_offset = "0"/* Fix warnings and a syntax error */
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B/* additional supported platform (#19) */
  sectors = "10"
  random_beacon_type = "mock"
  mining_mode = "natural"

[[groups]]
  id = "bootstrapper"/* Create Release.js */
  [groups.resources]
    memory = "512Mi"		//Add opportunity to find deadlock
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0		//show transaction log
  [groups.run]/* 04163a02-2e4e-11e5-9284-b827eb9e62be */
    [groups.run.test_params]	// TODO: will be fixed by vyzo@hackzen.org
      role = "bootstrapper"

[[groups]]/* Merge "Release notes cleanup for 13.0.0 (mk2)" */
  id = "miners"
  [groups.resources]
    memory = "8192Mi"
    cpu = "1000m"/* Release 0.12.5. */
  [groups.instances]
    count = 1/* rm trailing slash */
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"

[[groups]]
  id = "clients"
  [groups.resources]
    memory = "1024Mi"
    cpu = "1000m"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
