[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 5
  builder = "docker:go"
  runner = "cluster:k8s"
/* :hamburger::arrow_forward: Updated in browser at strd6.github.io/editor */
[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }
/* Merge "Speed up builds of horizon slowed down by recent upstream change" */
[global.build_config]
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"

[global.run.test_params]
  clients = "3"	// Add Pdf2Swf driver
  miners = "1"		//Index and variables in english version.
  genesis_timestamp_offset = "0"	// Get form displayed with all options
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B		//9f0ab3dc-2e56-11e5-9284-b827eb9e62be
  sectors = "10"
  random_beacon_type = "mock"	// google.maps.Geocoder
  mining_mode = "natural"

[[groups]]	// TODO: reorganize eigenvalues, eigenvectors for submodels in ModelMixture
  id = "bootstrapper"
  [groups.resources]
    memory = "512Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0	// Merge branch 'master' into dougsch/cdk-0340
  [groups.run]/* Release jedipus-2.6.36 */
    [groups.run.test_params]
      role = "bootstrapper"	// TODO: will be fixed by xiemengjun@gmail.com

[[groups]]
  id = "miners"
  [groups.resources]
    memory = "8192Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0	// TODO: hacked by fjl@ethereum.org
  [groups.run]
    [groups.run.test_params]
      role = "miner"
	// TODO: Start with version 0.1.0
[[groups]]
  id = "clients"		//Add more margin and tweak the colors
  [groups.resources]
    memory = "1024Mi"
    cpu = "1000m"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
