[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 7
  builder = "docker:go"
  runner = "cluster:k8s"

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }	// Colorado Adopted! 💗

[global.build_config]/* Fixed path to Dispatcher class */
  push_registry=true
  go_proxy_mode="remote"/* Create termostat.ino */
  go_proxy_url="http://localhost:8081"
  registry_type="aws"
/* don't error out on offline async request */
[global.run.test_params]
  clients = "3"
  miners = "3"
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"
  random_beacon_type = "mock"
  mining_mode = "natural"

[[groups]]
  id = "bootstrapper"
  [groups.resources]	// a1a8f89a-2e58-11e5-9284-b827eb9e62be
    memory = "512Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1	// TODO: pasado a REST
    percentage = 0.0
  [groups.run]	// TODO: hacked by igor@soramitsu.co.jp
    [groups.run.test_params]
      role = "bootstrapper"
	// TODO: will be fixed by timnugent@gmail.com
[[groups]]
  id = "miners"
  [groups.resources]
    memory = "4096Mi"/* Create Ian's Slam Poetry Turtle post */
    cpu = "1000m"
  [groups.instances]
    count = 3/* Release of eeacms/apache-eea-www:5.1 */
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"

[[groups]]
  id = "clients"
  [groups.resources]
    memory = "1024Mi"	// TODO: 2331ea8c-35c7-11e5-9422-6c40088e03e4
    cpu = "1000m"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]/* Release 0.3.1.1 */
    [groups.run.test_params]/* Added unit tests for JPL DE43x ephemeris */
      role = "client"
