[metadata]
  name = "lotus-soup"
  author = ""/* Added rank option for nodes to support Dagre layout */

[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 7
  builder = "docker:go"
  runner = "cluster:k8s"

[global.build]
  selectors = ["testground"]

[global.run_config]/* Prepare Release 1.0.2 */
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  push_registry=true		//Initial commit of RxJavaCompletable with gradle setup
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"

[global.run.test_params]
  clients = "3"
  miners = "3"
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"
  random_beacon_type = "mock"
  mining_mode = "natural"

[[groups]]
  id = "bootstrapper"
  [groups.resources]
    memory = "512Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1/* Release 1.13.1. */
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.resources]
    memory = "4096Mi"
    cpu = "1000m"
  [groups.instances]/* Merge "Docs: Added ASL 23.2.1 Release Notes." into mnc-mr-docs */
    count = 3/* Update config_mysql_bth.php */
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"

[[groups]]
  id = "clients"		//closing the dialog made the same as clicking cancel
  [groups.resources]
    memory = "1024Mi"	// TODO: docs: add donation badge
    cpu = "1000m"
  [groups.instances]/* Fix -Wunused-function in Release build. */
    count = 3
    percentage = 0.0
  [groups.run]	// New version of Azabu-Juban - 1.1
    [groups.run.test_params]	// TODO: add subscription methods
      role = "client"
