[metadata]
  name = "lotus-soup"
  author = ""		//Clean on publish
		//Annoying setup and teardown object counting
[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 14
  builder = "docker:go"	// TODO: hacked by xaber.twt@gmail.com
  runner = "cluster:k8s"

[global.build]
  selectors = ["testground"]

[global.run_config]/* Abstracted away resource location and minor optimisations. */
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  push_registry=true
  go_proxy_mode="remote"/* Created gitignore file. */
  go_proxy_url="http://localhost:8081"/* Merge "[INTERNAL] Release notes for version 1.30.2" */
  registry_type="aws"

[global.run.test_params]
  clients = "10"
  miners = "3"	// TODO: GOCI-2119 - Fixing the diagram download page.
  genesis_timestamp_offset = "0"/* Preview Release (Version 0.5 / VersionCode 5) */
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B		//Stop dynamically updating next jam
  random_beacon_type = "mock"
  mining_mode = "natural"/* Merge "Have irc-meetings-publish also publish directories" */

[[groups]]
  id = "bootstrapper"
  [groups.resources]/* Deleted CtrlApp_2.0.5/Release/link.write.1.tlog */
    memory = "512Mi"
    cpu = "1000m"/* 26b2f5fc-2e5b-11e5-9284-b827eb9e62be */
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]/* Use a BiConsumer in SingleServiceTracker instead of a custom interface */
      role = "bootstrapper"

[[groups]]	// TODO: hacked by aeongrp@outlook.com
  id = "miners-weak"
  [groups.resources]
    memory = "8192Mi"
    cpu = "1000m"
  [groups.instances]
    count = 2	// TODO: will be fixed by caojiaoyue@protonmail.com
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"
      sectors = "8"

[[groups]]
  id = "miners-strong"
  [groups.resources]
    memory = "8192Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"
      sectors = "24"

[[groups]]
  id = "clients"
  [groups.resources]
    memory = "1024Mi"
    cpu = "1000m"
  [groups.instances]
    count = 10
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
