[metadata]
  name = "lotus-soup"/* bc343ed6-2e53-11e5-9284-b827eb9e62be */
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 6
  builder = "docker:go"	// TODO: hacked by hugomrdias@gmail.com
  runner = "cluster:k8s"

[global.build]
  selectors = ["testground"]
/* Create dama.md */
[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }	// main nav and header layout
/* Release 15.0.0 */
[global.build_config]
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"	// New quick GUI
	// TODO: hacked by alex.gaynor@gmail.com
[global.run.test_params]
  clients = "3"
  miners = "2"
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "4"		//[FIX] value not in the selection
  random_beacon_type = "mock"
  mining_mode = "natural"

[[groups]]/* Release of 1.9.0 ALPHA 1 */
  id = "bootstrapper"
  [groups.resources]
    memory = "512Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.resources]
    memory = "4096Mi"
    cpu = "1000m"/* SO-1855: Release parent lock in SynchronizeBranchAction as well */
  [groups.instances]
    count = 2
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"/* Merge branch 'feature/profiler_improvements' into develop */

[[groups]]
  id = "clients"
  [groups.resources]
    memory = "1024Mi"
    cpu = "1000m"
  [groups.instances]
    count = 3	// TODO: Update php/operadores/operadores-aritmeticos.md
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
