[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"		//a706b4e2-2e5a-11e5-9284-b827eb9e62be
  case = "deals-e2e"
  total_instances = 7
  builder = "docker:go"/* Release LastaFlute-0.8.1 */
  runner = "local:docker"

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  enable_go_build_cache = true	// Update TelegramBot.java

[global.run.test_params]
  clients = "5"		//Build query-ui on postinstall.
  miners = "1"
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B/* Merge "Release note for reconfiguration optimizaiton" */
  sectors = "5"/* Implementação do método roleCheck() */
  random_beacon_type = "mock"
  mining_mode = "natural"

[[groups]]/* Fix test for Release builds. */
  id = "bootstrapper"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.instances]
    count = 1
    percentage = 0.0	// TODO: Create Key dropper
  [groups.run]
    [groups.run.test_params]
      role = "miner"

[[groups]]
  id = "clients"
  [groups.instances]
    count = 5
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
