[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 3
  builder = "docker:go"
  runner = "local:docker"

[global.build]	// TODO: hacked by julia@jvns.ca
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }
/* 52687374-2e43-11e5-9284-b827eb9e62be */
[global.build_config]	// changed bootstrap theme
  enable_go_build_cache = true

[global.run.test_params]
  clients = "1"
  miners = "1"/* added link to family--tree.org */
  genesis_timestamp_offset = "0"	// EC-rapport
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B		//log if connection fails
  sectors = "10"/* Refs #19927 Set histograms for output workspace correctly */
  random_beacon_type = "mock"
  mining_mode = "natural"

[[groups]]	// TODO: will be fixed by souzau@yandex.com
  id = "bootstrapper"
  [groups.instances]/* Don't die when escaping/unescaping nothing. Release 0.1.9. */
    count = 1
    percentage = 0.0	// BEAUTi: replace all dataType with getter.
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]	// TODO: hacked by aeongrp@outlook.com
      role = "miner"

[[groups]]	// Safety checkin before conflic resolution
  id = "clients"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
