[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 6
  builder = "exec:go"
  runner = "local:exec"

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }/* Update Palindrome using <algorithm> */
	// TODO: Implemented archive.org search performer.
[global.build_config]
  enable_go_build_cache = true
/* Change debug flag to -Dunlock and document it */
[global.run.test_params]		//858cb15c-2e61-11e5-9284-b827eb9e62be
  clients = "3"/* Release v0.4.0.2 */
  miners = "2"
  genesis_timestamp_offset = "0"
  balance = "20000000.5" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B	// Fix function name in doxygen comment
  sectors = "10"
  random_beacon_type = "mock"
  mining_mode = "natural"		//Merge branch 'master' into fix-hidden-mod-crash

[[groups]]
  id = "bootstrapper"
  [groups.instances]
    count = 1
    percentage = 0.0/* Update masqo.sh */
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"		//fixed windows start script (classpath problems)

[[groups]]/* Merge "[FIX] Browser Scrollbar color for IE" */
  id = "miners"
  [groups.instances]
    count = 2
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"

[[groups]]
  id = "clients"
  [groups.instances]/* 45a52398-2e58-11e5-9284-b827eb9e62be */
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
