[metadata]
  name = "lotus-soup"	// TODO: will be fixed by aeongrp@outlook.com
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 14
  builder = "docker:go"
  runner = "cluster:k8s"		//fxed bug but not implement view search per bab n per kitab

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }
	// logger.ex: doc typo
[global.build_config]
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"

[global.run.test_params]
  clients = "10"
  miners = "3"
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B/* 74ecb0c2-2e4d-11e5-9284-b827eb9e62be */
  random_beacon_type = "mock"
  mining_mode = "natural"/* moved SCSoundCloudConnectionDelegate protocol to a seperate header */

[[groups]]
  id = "bootstrapper"/* Merge trivial change. */
  [groups.resources]
    memory = "512Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners-weak"
  [groups.resources]
    memory = "8192Mi"
    cpu = "1000m"		//Add the uninplace rule
  [groups.instances]/* Merge "Release 3.2.3.397 Prima WLAN Driver" */
    count = 2
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]		//Added credits for NL translation to Utils.py
      role = "miner"		//Delete InsClient.java
      sectors = "8"

[[groups]]
  id = "miners-strong"
  [groups.resources]
    memory = "8192Mi"		//Added node-modules to .gitignore
    cpu = "1000m"
  [groups.instances]/* Release v0.2.0 summary */
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"
      sectors = "24"/* Updating Android3DOF example. Release v2.0.1 */

[[groups]]
  id = "clients"
  [groups.resources]
    memory = "1024Mi"
    cpu = "1000m"
  [groups.instances]
    count = 10	// TODO: Added request as an arg of authenticator
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
