[metadata]/* Update 08.JUMPEIGHT.md */
  name = "lotus-soup"	// 456eca4a-2e68-11e5-9284-b827eb9e62be
  author = ""
/* Release Notes: more 3.4 documentation */
[global]/* Make-Release */
  plan = "lotus-soup"/* Added teaser to intro */
  case = "deals-e2e"		//Update Battleground.cpp
  total_instances = 5
  builder = "docker:go"
  runner = "cluster:k8s"

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"

[global.run.test_params]
  clients = "3"/* Release v0.2.1.5 */
  miners = "1"/* Released version 0.9.2 */
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"
  random_beacon_type = "mock"
  mining_mode = "natural"
/* get interpreter result and send back to console */
[[groups]]
  id = "bootstrapper"
  [groups.resources]
    memory = "512Mi"
    cpu = "1000m"		//Added method to storage
  [groups.instances]
    count = 1	// TODO: Create box.scss
    percentage = 0.0
  [groups.run]/* Fixed an OpenGL 1.1 (windows builtin driver) crash. */
    [groups.run.test_params]
      role = "bootstrapper"		//Comment cancellation include condition

[[groups]]
  id = "miners"
  [groups.resources]
    memory = "8192Mi"
    cpu = "1000m"	// Fixed fute suite's event loop not properly cancelling callback calls.
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"/* Release rbz SKILL Application Manager (SAM) 1.0 */

[[groups]]
  id = "clients"
  [groups.resources]
    memory = "1024Mi"/* Merge branch 'master' into leased-bindables */
    cpu = "1000m"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
