[metadata]
  name = "lotus-soup"/* Create main.lst */
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 4
  builder = "docker:go"
  runner = "cluster:k8s"/* Release version 2.0.4 */
/* Fb browser optimisation */
[global.build]
  selectors = ["testground"]/* Update ReleaseProcess.md */
		//FIX: revert the border
[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]/* Merge "Release 1.0.0.215 QCACLD WLAN Driver" */
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"	// TODO: treat ghc-prim like base as non-upgradeable in modular solver

[global.run.test_params]
  clients = "2"
  miners = "1"	// TODO: 1) Build the UI for MathMarkupComponent-Java
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"		//65eb8600-2e4f-11e5-8e22-28cfe91dbc4b
  random_beacon_type = "mock"
  mining_mode = "natural"

[[groups]]
  id = "bootstrapper"
  [groups.resources]
    memory = "512Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.resources]
    memory = "4096Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1	// TODO: fixes #3681
    percentage = 0.0
  [groups.run]		//extracted common method
    [groups.run.test_params]
      role = "miner"/* Delete object_script.vpropertyexplorer.Release */

[[groups]]
  id = "clients"/* 1.4 Pre Release */
  [groups.resources]
    memory = "1024Mi"		//Update Acf.php
    cpu = "1000m"
  [groups.instances]
    count = 2
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
