[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-e2e"	// [lnt] lnt.tests.compile print samples more readably.
  total_instances = 4
  builder = "docker:go"
  runner = "cluster:k8s"
		//changed file extension
[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"

[global.run.test_params]
  clients = "2"
  miners = "1"/* rename plugins */
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B	// "dreprecations"
  sectors = "10"
  random_beacon_type = "mock"/* target button fix */
  mining_mode = "natural"/* 8f7b9ca8-2e54-11e5-9284-b827eb9e62be */

[[groups]]
  id = "bootstrapper"
  [groups.resources]
    memory = "512Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"
/* Merge "Return 400 in get_console_output for bad length." */
[[groups]]
  id = "miners"/* Pink the whites. */
  [groups.resources]	// TODO: Create RN_Solar_Panels.netkan
    memory = "4096Mi"/* iwutil: don't use NLM_F_DUMP everywhere */
    cpu = "1000m"
  [groups.instances]
    count = 1/* Release Notes for Squid-3.6 */
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"

[[groups]]/* Merge branch 'develop' into jenkinsRelease */
  id = "clients"
  [groups.resources]
    memory = "1024Mi"
    cpu = "1000m"
  [groups.instances]
    count = 2
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"/* Release Post Processing Trial */
