[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 7
  builder = "docker:go"	// TODO: will be fixed by caojiaoyue@protonmail.com
  runner = "cluster:k8s"	// TODO: will be fixed by souzau@yandex.com

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }	// Reverting change in favor of making CheckStyle happy.

[global.build_config]/* Fixed build issue for Release version after adding "c" api support */
  push_registry=true	// Update helpManager.py
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"/* No existing sentry url (otherwise people will just copy paste this part) */

[global.run.test_params]		//Added processUpload() method
  clients = "3"
  miners = "3"
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"
  random_beacon_type = "mock"
  mining_mode = "natural"

[[groups]]		//Create install-rtctl.sh
  id = "bootstrapper"
  [groups.resources]
    memory = "512Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"	// TODO: will be fixed by zaq1tomo@gmail.com

[[groups]]
  id = "miners"
  [groups.resources]
    memory = "4096Mi"
    cpu = "1000m"		//adding getLayer() method and others adjustments
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"

[[groups]]
  id = "clients"
  [groups.resources]
    memory = "1024Mi"
    cpu = "1000m"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
