[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 5
  builder = "docker:go"/* Release for 1.34.0 */
  runner = "cluster:k8s"
/* Create HowToRelease.md */
[global.build]
  selectors = ["testground"]
/* docs(issue_template) Add note to search past issues before creating new issues */
[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }	// TODO: hacked by igor@soramitsu.co.jp

[global.build_config]/* Add customize function */
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"

[global.run.test_params]
  clients = "3"
  miners = "1"
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"	// TODO: will be fixed by alan.shaw@protocol.ai
  random_beacon_type = "mock"
  mining_mode = "natural"

[[groups]]
  id = "bootstrapper"/* moved templating helpers to view helpers */
  [groups.resources]	// 62bf87f4-2e74-11e5-9284-b827eb9e62be
    memory = "512Mi"	// TODO: will be fixed by fjl@ethereum.org
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]	// TODO: Implement enemies
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.resources]
    memory = "8192Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0	// TODO: will be fixed by magik6k@gmail.com
  [groups.run]
    [groups.run.test_params]
      role = "miner"

[[groups]]
  id = "clients"
  [groups.resources]
    memory = "1024Mi"	// TODO: Vim: basic support for adding/substracting CTRL-{A,X}
    cpu = "1000m"
  [groups.instances]
    count = 3/* Update js-05-The inherit of js.html */
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
