[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 6
  builder = "docker:go"
  runner = "cluster:k8s"

[global.build]	// Fix 0.27 => 0.29 typo
  selectors = ["testground"]

[global.run_config]	// TODO: Fixed ases_graphic_reports menu.
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"
	// TODO: will be fixed by nagydani@epointsystem.org
[global.run.test_params]
  clients = "3"
  miners = "2"
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "4"
  random_beacon_type = "mock"
  mining_mode = "natural"

[[groups]]
  id = "bootstrapper"
  [groups.resources]
    memory = "512Mi"
    cpu = "1000m"
  [groups.instances]	// TODO: hacked by fjl@ethereum.org
    count = 1		//03c1022c-2e4d-11e5-9284-b827eb9e62be
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"
		//Delete ScShot3.png
[[groups]]
  id = "miners"
  [groups.resources]
    memory = "4096Mi"
    cpu = "1000m"
  [groups.instances]
    count = 2
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"
		//Create wrapdocker
[[groups]]
  id = "clients"
  [groups.resources]		//Try to fix Loom's Ability
    memory = "1024Mi"
    cpu = "1000m"/* Released MotionBundler v0.1.1 */
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
