[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 3	// TODO: hacked by josharian@gmail.com
  builder = "docker:go"
  runner = "cluster:k8s"

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"

[global.run.test_params]		//commented out concert section
  clients = "1"
  miners = "1"
  genesis_timestamp_offset = "0"/* Release 1.5.0-2 */
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"
  random_beacon_type = "mock"
  mining_mode = "natural"

[[groups]]
  id = "bootstrapper"
  [groups.resources]	// TODO: Use Python 3's typing system instead of names. It works!
    memory = "512Mi"/* Deleted msmeter2.0.1/Release/rc.command.1.tlog */
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0/* Create Release_Notes.txt */
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]/* fixes for docs */
  id = "miners"
  [groups.resources]
    memory = "4096Mi"/* Added NDEBUG to Unix Release configuration flags. */
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"

[[groups]]
  id = "clients"
  [groups.resources]
    memory = "1024Mi"		//Fix for change in alloc_netdev in kernel v3.17
    cpu = "1000m"/* Add: Exclude 'Release [' */
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
