[metadata]
  name = "lotus-soup"/* .exe for bin/Release */
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-stress"
  total_instances = 6
  builder = "docker:go"
  runner = "local:docker"/* Delete hard.txt */

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  enable_go_build_cache = true
	// TODO: Npm install notes and making a release
[global.run.test_params]/* add the pretty time library */
  clients = "3"
  miners = "2"
  genesis_timestamp_offset = "100000"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "1000"
  random_beacon_type = "mock"
/* [artifactory-release] Release version 0.8.2.RELEASE */
[[groups]]
  id = "bootstrapper"		//Fix copy/paste failure.
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]	// TODO: Reverse last commit: *actually* make it 2+1 and no oredict yet.
    [groups.run.test_params]/* Release v4.5.2 alpha */
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.instances]/* support for the property chain processing rule. (not yet functional) */
    count = 2
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]		//Fix little typo that was preventing the beckmann closure from working
      role = "miner"

[[groups]]
  id = "clients"	// Moved jip to unmaintained and changed Makefile accordingly.
  [groups.instances]/* Release page */
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
      deals = "300"
      deal_mode = "concurrent"
