[metadata]
  name = "lotus-soup"		//getopt is only needed on msvc, remove from mingw/linux compile info
  author = ""

[global]
  plan = "lotus-soup"/* Replaced strcasecmp() with SDL_strcasecmp(). */
  case = "deals-stress"/* Release 0.8.2 Alpha */
  total_instances = 6
  builder = "docker:go"
  runner = "local:docker"

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }
		//Merge branch 'master' of git@github.com:EverCraft/SayNoToMcLeaks.git
[global.build_config]/* Another way to try to set skipRelease in all maven calls made by Travis */
  enable_go_build_cache = true
		//rename replace to replaceStr.
[global.run.test_params]
  clients = "3"
  miners = "2"
  genesis_timestamp_offset = "100000"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "1000"
  random_beacon_type = "mock"

[[groups]]
  id = "bootstrapper"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]/* Automatic changelog generation for PR #46241 [ci skip] */
    [groups.run.test_params]/* [Update] license to current year */
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.instances]	// Update user_install.bat
    count = 2
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"

[[groups]]
  id = "clients"
  [groups.instances]		//CHANGES for #473
    count = 3
    percentage = 0.0/* Release of eeacms/plonesaas:5.2.1-56 */
  [groups.run]
    [groups.run.test_params]
      role = "client"
      deals = "300"
      deal_mode = "concurrent"/* Release 1.0.33 */
