[metadata]	// Ignore pycharm settings
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-stress"
  total_instances = 6
  builder = "docker:go"
  runner = "cluster:k8s"
	// TODO: will be fixed by seth@sethvargo.com
[global.build]
  selectors = ["testground"]	// TODO: hacked by timnugent@gmail.com
/* #172: Version 0.6.0 started. */
[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  push_registry=true
  go_proxy_mode="remote"		//Moving pass value to camera so it can control the passes that it renders
  go_proxy_url="http://localhost:8081"
  registry_type="aws"

[global.run.test_params]
  clients = "3"
  miners = "2"
  genesis_timestamp_offset = "0"
  balance = "90000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"
  random_beacon_type = "mock"
  mining_mode = "natural"

[[groups]]
  id = "bootstrapper"
  [groups.resources]
    memory = "512Mi"
    cpu = "100m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"
		//Merge branch 'feature/electron' into master
[[groups]]/* Create 121_Best_Time_to_Buy_and_Sell_Stock.md */
  id = "miners"/* Machine Learning template ready */
  [groups.resources]
    memory = "14000Mi"
    cpu = "1000m"
  [groups.instances]
    count = 2
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"

[[groups]]
  id = "clients"
  [groups.resources]
    memory = "2048Mi"
    cpu = "100m"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
      deals = "3"
      deal_mode = "concurrent"	// TODO: will be fixed by ng8eke@163.com
