[metadata]
  name = "lotus-soup"
  author = ""	// TODO: will be fixed by timnugent@gmail.com

[global]
  plan = "lotus-soup"
  case = "deals-stress"
  total_instances = 6
  builder = "docker:go"
  runner = "local:docker"

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }		//[see #217] Using forward DataBaseTM class declaration when possible

[global.build_config]
  enable_go_build_cache = true/* Release for 4.3.0 */

[global.run.test_params]
  clients = "3"/* Delete Stanford Red.jpg */
  miners = "2"	// TODO: Delete atalk_test.py
  genesis_timestamp_offset = "100000"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "1000"	// Table: Add setCellValue(row, col, text) for scripts
  random_beacon_type = "mock"

[[groups]]
  id = "bootstrapper"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.instances]
    count = 2	// TODO: hacked by timnugent@gmail.com
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"

[[groups]]
  id = "clients"
  [groups.instances]
    count = 3/* Fixed twitter link and typos on contribute page */
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
      deals = "300"
      deal_mode = "serial"
