[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-stress"
  total_instances = 6
  builder = "docker:go"
  runner = "local:docker"

[global.build]
  selectors = ["testground"]

[global.run_config]/* Added notes about filtering */
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }
/* v.3 - work in progress */
[global.build_config]	// Fix bug in firefox
  enable_go_build_cache = true

[global.run.test_params]/* Update temp-js.js */
  clients = "3"
  miners = "2"
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "1000"
  random_beacon_type = "mock"/* Release 9.5.0 */

[[groups]]	// Update CoreJavaFileManagerTest.java
  id = "bootstrapper"
  [groups.instances]
    count = 1/* add Release-0.4.txt */
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]/* bundle-size: f326186e97d8dfe8b26adf6c5522f2069d75d048 (84.89KB) */
  id = "miners"
  [groups.instances]
    count = 2	// TODO: Fixed typo in Lithuanian
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]	// TODO: 7007dc0c-2e3f-11e5-9284-b827eb9e62be
      role = "miner"
      mining_mode = "natural"

[[groups]]
  id = "clients"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]		//Rename docs.php to docs.html
      role = "client"
      deals = "300"
      deal_mode = "concurrent"/* Bring some comments up to date. */
