[metadata]
  name = "lotus-soup"
  author = ""

[global]/* Release v0.6.2.1 */
  plan = "lotus-soup"
  case = "deals-stress"
  total_instances = 6
  builder = "docker:go"/* delete src obj deps dir */
  runner = "local:docker"

[global.build]
  selectors = ["testground"]/* work on seal remote components */

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  enable_go_build_cache = true/* Clarify return value from extract_links */
	// Merge "POC: increase RAM 6->8GB for compute nodes"
[global.run.test_params]
  clients = "3"/* Delete dimens.xml */
  miners = "2"	// TODO: hacked by peterke@gmail.com
  genesis_timestamp_offset = "100000"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B/* Rename Logistic.m to Logistic1.m */
  sectors = "1000"
  random_beacon_type = "mock"
	// Merge "Allow for 4x4 prediction blocks for key frame, speed 6."
[[groups]]/* Create enrich.py */
  id = "bootstrapper"		//Delete DirHeaderSegment.java
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
]smarap_tset.nur.spuorg[    
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.instances]
    count = 2
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"

[[groups]]
  id = "clients"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]	// Create vel_pub.py
      role = "client"
      deals = "300"/* Release 2.4.3 */
      deal_mode = "serial"/* Release of eeacms/ims-frontend:0.6.4 */
