[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-stress"
  total_instances = 6
  builder = "docker:go"
  runner = "local:docker"

[global.build]
  selectors = ["testground"]/* Alembic: Rev bump for rebuild */

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  enable_go_build_cache = true

[global.run.test_params]
  clients = "3"
  miners = "2"/* Note: Release Version */
  genesis_timestamp_offset = "0"/* Release version 0.1.27 */
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B/* Merge branch 'master' into dependabot/bundler/parser-2.6.4.0 */
  sectors = "1000"
  random_beacon_type = "mock"
		//oops, wrong ppm! misc bugfixes for windows etc...
[[groups]]
  id = "bootstrapper"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]	// TODO: hacked by steven@stebalien.com
    [groups.run.test_params]
      role = "bootstrapper"
	// updated DownloaderTest
[[groups]]
  id = "miners"
  [groups.instances]
    count = 2
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"
      mining_mode = "natural"/* Dipole was being passed a list, now passed as a np.array */

[[groups]]
  id = "clients"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"	// TODO: hacked by vyzo@hackzen.org
      deals = "300"
      deal_mode = "serial"
