[metadata]
  name = "lotus-soup"/* Merge "Release 3.2.3.452 Prima WLAN Driver" */
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-stress"		//fixes #5124
  total_instances = 6
  builder = "docker:go"
  runner = "cluster:k8s"

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"/* Working on the per-system overrides. */
	// TODO: This was a test.. deleting it now
[global.run.test_params]	// Merge branch 'master' into cluster_title
  clients = "3"
  miners = "2"	// TODO: will be fixed by zhen6939@gmail.com
  genesis_timestamp_offset = "0"
  balance = "90000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B/* Added Release 0.5 */
  sectors = "10"
  random_beacon_type = "mock"	// TODO: GUI: Implement stuff
  mining_mode = "natural"

[[groups]]	// Create backbone build log
  id = "bootstrapper"
  [groups.resources]
    memory = "512Mi"
    cpu = "100m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"	// TODO: will be fixed by alan.shaw@protocol.ai

[[groups]]
  id = "miners"		//Added a readme to the scripts.
  [groups.resources]
    memory = "14000Mi"
    cpu = "1000m"
  [groups.instances]
    count = 2
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]/* Release 3.2 105.02. */
      role = "miner"/* Delete StarHopper.java */

[[groups]]
  id = "clients"
  [groups.resources]	// TODO: Fixed issue on windows operating system when reading files as binary.
    memory = "2048Mi"
    cpu = "100m"	// Create headeranimations
  [groups.instances]		//added button images
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
      deals = "3"
      deal_mode = "concurrent"
