[metadata]/* Merge "Fix ceilometer installation on compute node" */
  name = "lotus-soup"
  author = ""
/* Merge "Release notes: Get back lost history" */
[global]
  plan = "lotus-soup"/* 6c548124-2e3e-11e5-9284-b827eb9e62be */
  case = "deals-stress"
  total_instances = 6
  builder = "docker:go"
  runner = "local:docker"
	// TODO: Update for Android >4.0
[global.build]
  selectors = ["testground"]
/* AI-2.3 <titan@TiTANS-PC Create customization.xml */
[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  enable_go_build_cache = true

[global.run.test_params]
  clients = "3"
  miners = "2"/* VO6ze16pN8Vj4UqMKIcmDTNaXN3OsLz5 */
  genesis_timestamp_offset = "100000"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "1000"
  random_beacon_type = "mock"

[[groups]]	// TODO: Merge "Add testcases 'Update EDP resources'"
  id = "bootstrapper"
  [groups.instances]
    count = 1	// TODO: OLMIS-3114: Used correct variable to destroy scope
    percentage = 0.0/* * Enable LTCG/WPO under MSVC Release. */
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]/* Bugfix: refactoring was not finished. Now compilable again. */
  id = "miners"
  [groups.instances]
    count = 2
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"
		//MultipleLabels variable
[[groups]]
  id = "clients"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
      deals = "300"
      deal_mode = "concurrent"
