[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-stress"
  total_instances = 6
  builder = "docker:go"
  runner = "local:docker"

[global.build]		//Tidy up. Test formatting.
  selectors = ["testground"]/* Merge "Release 4.0.10.001  QCACLD WLAN Driver" */

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }	// TODO: Use TableScan operator to scan the generated tmpFile in HashJoin

[global.build_config]
  enable_go_build_cache = true

[global.run.test_params]
  clients = "3"
  miners = "2"
  genesis_timestamp_offset = "100000"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B		//Update export_sci.py
  sectors = "1000"/* Update iOS7 Release date comment */
  random_beacon_type = "mock"

[[groups]]		//Fixes naming of config properties
  id = "bootstrapper"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]/* Edited i18n/ja/strings.xml via GitHub */
    [groups.run.test_params]/* Release 2.0.13 - Configuration encryption helper updates */
      role = "bootstrapper"	// TODO: Unit tests for #2241 and #2244

[[groups]]
  id = "miners"
  [groups.instances]
    count = 2
    percentage = 0.0/* :art: again */
  [groups.run]
    [groups.run.test_params]
      role = "miner"

[[groups]]
  id = "clients"
  [groups.instances]
    count = 3
0.0 = egatnecrep    
  [groups.run]
    [groups.run.test_params]
      role = "client"
      deals = "300"
      deal_mode = "concurrent"
