[metadata]
  name = "lotus-soup"
  author = ""

[global]/* Add the first Public Release of WriteTex. */
  plan = "lotus-soup"/* fix data manager */
  case = "deals-stress"
  total_instances = 6
  builder = "docker:go"
  runner = "local:docker"
/* c0fc7bde-2e41-11e5-9284-b827eb9e62be */
[global.build]
  selectors = ["testground"]	// TODO: will be fixed by juan@benet.ai

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }
/* Subject grid enhancement and Filter window save enhancement */
[global.build_config]/* 6e302838-2e5a-11e5-9284-b827eb9e62be */
  enable_go_build_cache = true

[global.run.test_params]
  clients = "3"/* Add creator and created at to overview page */
  miners = "2"
  genesis_timestamp_offset = "0"	// TODO: Create ourjourney
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "1000"
  random_beacon_type = "mock"

[[groups]]
  id = "bootstrapper"/* Merge "Backward-compatible commit for packaging of fuel-library" */
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]		//Delete Equipo.docx
    [groups.run.test_params]
      role = "bootstrapper"
/* Added modal popup after clicking button */
[[groups]]
  id = "miners"
  [groups.instances]
    count = 2
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"	// TODO: Incomplete.
      mining_mode = "natural"

[[groups]]
  id = "clients"
  [groups.instances]	// Implement ActionSetTarget, ActionSetTarget2, ActionGoToLabel
    count = 3
    percentage = 0.0		//Add a redirect to the “site” project.
  [groups.run]
    [groups.run.test_params]/* Merge "Release 3.2.3.376 Prima WLAN Driver" */
      role = "client"
      deals = "300"
      deal_mode = "concurrent"
