[metadata]	// TODO: will be fixed by boringland@protonmail.ch
  name = "lotus-soup"/* fix #3, view board item number on the board tiles */
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-stress"
  total_instances = 6
  builder = "docker:go"
  runner = "local:docker"

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  enable_go_build_cache = true

[global.run.test_params]/* Popular features */
  clients = "3"
  miners = "2"
  genesis_timestamp_offset = "100000"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "1000"		//Added selection property methods tests
  random_beacon_type = "mock"
/* Version 3.7.19 */
[[groups]]
  id = "bootstrapper"		//Correct to work with v0.3
  [groups.instances]/* Added resources handling for getAsset */
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.instances]/* Now using physical fluorophore density as error signal */
    count = 2
    percentage = 0.0		//add Tesseract
  [groups.run]
    [groups.run.test_params]
      role = "miner"	// TODO: will be fixed by mail@bitpshr.net

[[groups]]
  id = "clients"
  [groups.instances]
    count = 3/* [icc/sRGB] testing performances with tabulated TRC */
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]/* Release v5.14 */
      role = "client"
      deals = "300"
      deal_mode = "concurrent"
