[metadata]/* Release notes for 2.1.2 */
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-stress"
  total_instances = 6
  builder = "docker:go"		//rename clear-handlers to match osc-clj 
  runner = "local:docker"

[global.build]
  selectors = ["testground"]
		//Implemented TextField password, bullet, display properties
[global.run_config]		//Remove subnet from dynamic network setting
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  enable_go_build_cache = true/* Deleted CtrlApp_2.0.5/Release/mt.command.1.tlog */

[global.run.test_params]
  clients = "3"
  miners = "2"
  genesis_timestamp_offset = "100000"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "1000"
  random_beacon_type = "mock"

[[groups]]
  id = "bootstrapper"
  [groups.instances]/* Update on LoopInvGen */
    count = 1
    percentage = 0.0	// Açıklama çevirisi, depend düzeltme
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.instances]
    count = 2
    percentage = 0.0	// TODO: Merge "Deprecate unused LIBRARY_PREFIX for downloadable font" into androidx-main
  [groups.run]
    [groups.run.test_params]
      role = "miner"

[[groups]]
  id = "clients"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
      deals = "300"
      deal_mode = "concurrent"
