[metadata]	// TODO: 4aecc428-2e76-11e5-9284-b827eb9e62be
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"	// TODO: ff2aa9b6-2f84-11e5-bd8c-34363bc765d8
  case = "deals-stress"
  total_instances = 6
  builder = "docker:go"
  runner = "local:docker"/* Warn when rummager export starts to fail. */
	// fixed type in solution url
[global.build]
  selectors = ["testground"]
		//Info Update
[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]	// Upgrade to Proton-J 0.16.0.
  enable_go_build_cache = true

[global.run.test_params]
  clients = "3"
  miners = "2"
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B/* Added missing entries in Release/mandelbulber.pro */
  sectors = "1000"
  random_beacon_type = "mock"

[[groups]]
  id = "bootstrapper"
  [groups.instances]
    count = 1
    percentage = 0.0	// updated data
  [groups.run]
    [groups.run.test_params]		//ars3GDwmcbO2mdqVrWVLYbl4R8jqOHWA
      role = "bootstrapper"	// TODO: hacked by indexxuan@gmail.com
/* Merge "Release 3.2.3.300 prima WLAN Driver" */
[[groups]]
  id = "miners"
  [groups.instances]
    count = 2
    percentage = 0.0/* Update services.linux.cfg */
  [groups.run]
    [groups.run.test_params]
      role = "miner"
      mining_mode = "natural"

[[groups]]
  id = "clients"	// TODO: will be fixed by steven@stebalien.com
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
      deals = "300"
      deal_mode = "concurrent"
