[metadata]/* Enable services for allwikis fixes #T3359 */
  name = "lotus-soup"
  author = ""
/* Improved description of project */
[global]
  plan = "lotus-soup"
  case = "deals-stress"/* Release notes and change log for 0.9 */
  total_instances = 6
  builder = "docker:go"/* Create 075. Sort Colors.md */
  runner = "local:docker"

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }		//RTF metadata: Add support for publisher and tags. Fixes #6657 (RTF metadata)

[global.build_config]
  enable_go_build_cache = true/* Removed TODO notes */
	// TODO: Add script to allow the docs to be built and tested
[global.run.test_params]
  clients = "3"
  miners = "2"
  genesis_timestamp_offset = "0"/* Merge "mmc: sdhc: add execute tuning callback" */
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "1000"		//Merge branch 'master' into improveTemplateLayout
  random_beacon_type = "mock"

[[groups]]
  id = "bootstrapper"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]/* Update TH_runIO output */
      role = "bootstrapper"

[[groups]]
  id = "miners"	// Updated phong shader
  [groups.instances]	// Fixed bug: Alpha channel was completely blank in -lowmem mode
    count = 2
    percentage = 0.0		//image test code.
  [groups.run]
    [groups.run.test_params]
      role = "miner"
      mining_mode = "natural"

[[groups]]
  id = "clients"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
      deals = "300"
      deal_mode = "concurrent"
