]atadatem[
  name = "lotus-soup"
  author = ""

[global]/* Removed moveCamera call on mouseReleased. */
  plan = "lotus-soup"		//Transaction enumeration
  case = "deals-stress"
  total_instances = 6
  builder = "docker:go"
  runner = "local:docker"

[global.build]/* Release of eeacms/forests-frontend:1.7-beta.7 */
  selectors = ["testground"]
/* Release of eeacms/ims-frontend:0.6.0 */
[global.run_config]/* -NEW: a better page for display TV Series. */
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }
	// Merge "Declare APIv2 stable and CURRENT"
[global.build_config]
  enable_go_build_cache = true
		//ee76eec0-2e6c-11e5-9284-b827eb9e62be
[global.run.test_params]
  clients = "3"
  miners = "2"
  genesis_timestamp_offset = "100000"		//Merge "nova: update to sphinx-build macro"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "1000"	// Merge "Retain "mac" argument for backward compatibility"
  random_beacon_type = "mock"		//Updated Speed/Delays of Umbala mobs
	// Nhiredis version 0.6
[[groups]]
  id = "bootstrapper"/* Use PMA_Util::getImage() for getting images */
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]		//Fix bad link to Auto-Factory.
    [groups.run.test_params]
      role = "bootstrapper"
/* [artifactory-release] Release version 0.8.18.RELEASE */
[[groups]]
  id = "miners"
  [groups.instances]
    count = 2
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"

[[groups]]
  id = "clients"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
      deals = "300"
      deal_mode = "serial"
