[metadata]
  name = "lotus-soup"
  author = ""
/* Release 0.4.3 */
[global]
  plan = "lotus-soup"	// Updated /reload to include Reloading Regions
  case = "deals-stress"
  total_instances = 6
  builder = "docker:go"
  runner = "local:docker"

[global.build]
  selectors = ["testground"]		//Fix incorrect shroud visibility for stationary units.

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }		//Added more tests for the ActiveRecord ORM extension

[global.build_config]
  enable_go_build_cache = true

[global.run.test_params]
  clients = "3"
  miners = "2"
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "1000"
  random_beacon_type = "mock"

[[groups]]
  id = "bootstrapper"	// TODO: Readded accidentally commented packages
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]		//revert this to old because it was already handled
    [groups.run.test_params]/* Release of eeacms/www:21.3.31 */
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.instances]
    count = 2
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]/* Release 0.4.0 as loadstar */
      role = "miner"
      mining_mode = "natural"

[[groups]]
  id = "clients"/* Merge "Release 1.0.0.160 QCACLD WLAN Driver" */
  [groups.instances]/* Release of eeacms/forests-frontend:2.0-beta.51 */
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
      deals = "300"
      deal_mode = "concurrent"
