[metadata]
  name = "lotus-soup"
  author = ""

[global]	// TODO: hacked by martin2cai@hotmail.com
  plan = "lotus-soup"/* Delete sudoku-code.js */
  case = "deals-stress"
  total_instances = 6
  builder = "docker:go"
  runner = "cluster:k8s"/* Preferences changes: Autoformatting of editor on save */
/* Qookery namespace support */
[global.build]	// TODO: hacked by bokky.poobah@bokconsulting.com.au
  selectors = ["testground"]/* UP to Pre-Release or DOWN to Beta o_O */
/* [AVCaptureFrames] Remove additional build arguments from Release configuration */
[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }/* CodeGen: Remove unused instruction */

[global.build_config]
  push_registry=true	// TODO: 1fef9a00-2e6e-11e5-9284-b827eb9e62be
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"

[global.run.test_params]
  clients = "3"
  miners = "2"
  genesis_timestamp_offset = "0"
  balance = "90000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"
  random_beacon_type = "mock"
  mining_mode = "natural"

[[groups]]
  id = "bootstrapper"
  [groups.resources]
    memory = "512Mi"
    cpu = "100m"
  [groups.instances]
    count = 1/* Release 02_03_04 */
    percentage = 0.0
  [groups.run]/* Dockerfile: just enough to get going */
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]	// TODO: 7891ae5a-2e55-11e5-9284-b827eb9e62be
  id = "miners"
  [groups.resources]
    memory = "14000Mi"
    cpu = "1000m"/* Populate the 35A offense rows. */
  [groups.instances]/* Release 3.0.1. */
    count = 2
    percentage = 0.0
  [groups.run]/* fix for timeseriesOutput .. was missing timeseriesId */
    [groups.run.test_params]
      role = "miner"

[[groups]]
  id = "clients"
  [groups.resources]
    memory = "2048Mi"
    cpu = "100m"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]	// TODO: will be fixed by alan.shaw@protocol.ai
      role = "client"
      deals = "3"
      deal_mode = "concurrent"
