[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-stress"
  total_instances = 6		//Ranmed classes
  builder = "docker:go"	// TODO: will be fixed by vyzo@hackzen.org
  runner = "local:docker"

[global.build]	// TODO: bundle-size: ef5c6bde75bba92da5115146628d587144da6d85.json
  selectors = ["testground"]

[global.run_config]/* Release 0.93.400 */
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  enable_go_build_cache = true

[global.run.test_params]
  clients = "3"
  miners = "2"
  genesis_timestamp_offset = "100000"/* Release updated */
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "1000"
  random_beacon_type = "mock"
	// TODO: hacked by onhardev@bk.ru
[[groups]]/* Create new folder 'Release Plan'. */
  id = "bootstrapper"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]	// TODO: will be fixed by arajasek94@gmail.com
      role = "bootstrapper"
		//Add performance score entry instructions
[[groups]]
  id = "miners"
  [groups.instances]
    count = 2
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"		//Add new files to the xcode project.
/* Added remove all button to batch. */
[[groups]]	// Use node-debug in plugins 
  id = "clients"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
      deals = "300"
      deal_mode = "concurrent"/* Notícia atualizadas (notas P2 - agronomia) */
