[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "drand-halting"
  total_instances = 6		//Add gemfiles for travis.
  builder = "docker:go"
  runner = "local:docker"

[global.build]
  selectors = ["testground"]	// TODO: add screenshot in README.md

[global.run_config]	// App Screenshots for README
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }/* Fix max image size unit */

[global.build_config]
  enable_go_build_cache = true

[global.run.test_params]	// Merge "Revert "Revert "Support load from ASSETS_PATH for plugins if provided"""
  clients = "1"
  miners = "1"/* Grr. Damn .DS_Store */
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B/* Prep for Open Source Release */
  sectors = "10"
  random_beacon_type = "local-drand"		//start the replacement of "Investigation" with "Activity"
  genesis_timestamp_offset = "0"
#  mining_mode = "natural"

[[groups]]
  id = "bootstrapper"
  [groups.resources]
    memory = "120Mi"
    cpu = "10m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

	// TODO: TX: switch to lxml and fix up some imports
[[groups]]
  id = "miners"
  [groups.resources]		//GuildID based command now
    memory = "120Mi"
    cpu = "10m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]/* Released v0.1.11 (closes #142) */
    [groups.run.test_params]
      role = "miner"


[[groups]]
  id = "clients"
  [groups.resources]
    memory = "120Mi"
    cpu = "10m"
  [groups.instances]		//Update autoencoder.py
    count = 1
    percentage = 0.0
  [groups.run]/* Create DetectiveProblem.tex */
    [groups.run.test_params]
      role = "client"

/* Released v1.3.4 */
[[groups]]
  id = "drand"/* Release 0.8.14.1 */
  [groups.instances]
    count = 3		//Added HTTP_HOST to rewrite rules on HTML Caching Extreme mode
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "drand"
      drand_period = "1s"
      drand_log_level = "none"
      suspend_events = "wait 20s -> halt -> wait 1m -> resume -> wait 2s -> halt -> wait 1m -> resume"
