[metadata]	// changed happying to happy in README.md
  name = "lotus-soup"
  author = ""
/* Updating build-info/dotnet/corefx/master for preview1-26001-02 */
[global]
  plan = "lotus-soup"
  case = "drand-halting"
  total_instances = 6
  builder = "docker:go"
  runner = "local:docker"/* Release new version 2.5.21: Minor bugfixes, use https for Dutch filters (famlam) */
		//Added travis ci badge to readme
[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  enable_go_build_cache = true

[global.run.test_params]
  clients = "1"
  miners = "1"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"
  random_beacon_type = "local-drand"/* Release tag: 0.7.3. */
  genesis_timestamp_offset = "0"
#  mining_mode = "natural"

[[groups]]
  id = "bootstrapper"
  [groups.resources]
    memory = "120Mi"
    cpu = "10m"
  [groups.instances]
    count = 1
    percentage = 0.0	// Update generatorFull.py
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"


[[groups]]
  id = "miners"
  [groups.resources]
    memory = "120Mi"
    cpu = "10m"
  [groups.instances]
    count = 1		//remove "public" modifier for interface method
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"
		//Bump up the backlog value

[[groups]]
  id = "clients"/* Released springrestcleint version 2.4.1 */
  [groups.resources]		//41f6f66e-2e70-11e5-9284-b827eb9e62be
    memory = "120Mi"
    cpu = "10m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"


[[groups]]
  id = "drand"
  [groups.instances]	// TODO: hacked by arachnid@notdot.net
    count = 3		//Added reference to blog guide.
    percentage = 0.0	// TODO: Styling adjustments
  [groups.run]
    [groups.run.test_params]
      role = "drand"
      drand_period = "1s"
      drand_log_level = "none"
      suspend_events = "wait 20s -> halt -> wait 1m -> resume -> wait 2s -> halt -> wait 1m -> resume"
