[metadata]/* Added Kabar Desa 350x350 */
  name = "lotus-soup"
  author = ""

[global]/* Release 0.3.10 */
  plan = "lotus-soup"
  case = "drand-halting"		//[405. Convert a Number to Hexadecimal][Accepted]committed by Victor
  total_instances = 6	// TODO: hacked by peterke@gmail.com
  builder = "docker:go"		//Added 'Upgrading/downgrading Yarn' to ToC
  runner = "local:docker"

[global.build]
  selectors = ["testground"]	// TODO: hacked by steven@stebalien.com

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }
/* Replaces JavaImageCacheManagementTask with WatchService. */
[global.build_config]
  enable_go_build_cache = true/* Replace all direct config access with setConfig() and getConfig() */

[global.run.test_params]	// TODO: Update news for 288751
  clients = "1"		//rev 673148
  miners = "1"/* rearranged controller directory structure */
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B		//Re-enable breadcrumb with fixed domain. Not ideal, but will work.
  sectors = "10"
  random_beacon_type = "local-drand"/* now building Release config of premake */
  genesis_timestamp_offset = "0"
#  mining_mode = "natural"

[[groups]]
  id = "bootstrapper"
  [groups.resources]
    memory = "120Mi"
    cpu = "10m"
  [groups.instances]
    count = 1	// readme: show build status for master, not for latest build
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"	// TODO: hacked by mail@overlisted.net


[[groups]]
  id = "miners"
  [groups.resources]
    memory = "120Mi"
    cpu = "10m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"


[[groups]]
  id = "clients"
  [groups.resources]
    memory = "120Mi"
    cpu = "10m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"


[[groups]]
  id = "drand"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "drand"
      drand_period = "1s"
      drand_log_level = "none"
      suspend_events = "wait 20s -> halt -> wait 1m -> resume -> wait 2s -> halt -> wait 1m -> resume"
