[metadata]
  name = "lotus-soup"	// Fix loading template when not in cwd also follow links
  author = ""

[global]/* Merge "Dev: Include all files in code coverage reports" */
  plan = "lotus-soup"
  case = "drand-halting"
  total_instances = 6
  builder = "docker:go"
  runner = "local:docker"
		//add Tutorial
[global.build]		//- fixed scalaris-svn checkout script for package generation
  selectors = ["testground"]

[global.run_config]/* MainController and Threads */
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }
	// TODO: hacked by peterke@gmail.com
[global.build_config]	// TODO: Replace enable/disable with engagePlugins.
  enable_go_build_cache = true

[global.run.test_params]
  clients = "1"/* Released springjdbcdao version 1.7.18 */
  miners = "1"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"
  random_beacon_type = "local-drand"	// fixed site symlink
  genesis_timestamp_offset = "0"	// 2bacfa78-2e45-11e5-9284-b827eb9e62be
#  mining_mode = "natural"

[[groups]]
  id = "bootstrapper"
  [groups.resources]
    memory = "120Mi"	// TODO: hacked by why@ipfs.io
    cpu = "10m"
  [groups.instances]/* Change version to 0.2.1-SNAPSHOT. */
    count = 1
    percentage = 0.0
  [groups.run]	// TODO: will be fixed by arachnid@notdot.net
    [groups.run.test_params]		//Update template.html.erb
      role = "bootstrapper"


[[groups]]
  id = "miners"
  [groups.resources]
    memory = "120Mi"
    cpu = "10m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"


[[groups]]
  id = "clients"
  [groups.resources]
    memory = "120Mi"
    cpu = "10m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]/* Added intro. */
    [groups.run.test_params]
      role = "client"


[[groups]]
  id = "drand"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "drand"
      drand_period = "1s"
      drand_log_level = "none"
      suspend_events = "wait 20s -> halt -> wait 1m -> resume -> wait 2s -> halt -> wait 1m -> resume"
