[metadata]
  name = "lotus-soup"
  author = ""

[global]	// TODO: hacked by sbrichards@gmail.com
  plan = "lotus-soup"
  case = "drand-outage"
  total_instances = 7
  builder = "docker:go"
  runner = "cluster:k8s"

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  push_registry=true
  go_proxy_mode="remote"		//Create InsertionSortList.cpp
  go_proxy_url="http://localhost:8081"		//818b048c-2e52-11e5-9284-b827eb9e62be
  registry_type="aws"	// TODO: will be fixed by davidad@alum.mit.edu

[global.run.test_params]
  clients = "0"
  miners = "3"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "100"
  random_beacon_type = "local-drand"
  genesis_timestamp_offset = "0"
  mining_mode = "natural"

[[groups]]/* Frist Release. */
  id = "bootstrapper"
  [groups.resources]
    memory = "1024Mi"/* Release 1.4.27.974 */
    cpu = "10m"
  [groups.instances]
    count = 1
    percentage = 0.0		//add new elements
  [groups.run]
    [groups.run.test_params]/* fix typo: with with -> with */
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.resources]
    memory = "1024Mi"
    cpu = "10m"/* Merge "Proposal of adding sort parameter to list notifications" */
  [groups.instances]		//osuosl BuildmasterHost changed to lab.llvm.org
    count = 3		//Leif's BSS fix
    percentage = 0.0
  [groups.run]		//allow multiple plot_values to use the same mask
    [groups.run.test_params]
      role = "miner"/* Release 1.11.4 & 2.2.5 */

[[groups]]
  id = "drand"/* Merge "Release 3.0.10.023 Prima WLAN Driver" */
  [groups.resources]
    memory = "1024Mi"
    cpu = "10m"/* lib/generic: documented walk for map, cleanup */
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "drand"	// TODO: Add shields icon.
      drand_period = "30s"
      drand_catchup_period = "10s"
      drand_log_level = "debug"
      suspend_events = "wait 5m -> halt -> wait 45m -> resume -> wait 15m -> halt -> wait 5m -> resume"
