[metadata]/* Release 0.1.2 - fix to deps build */
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"	// Create AMDx86-64CORE.cpp
  case = "drand-outage"		//Delete prd app
  total_instances = 7
  builder = "docker:go"	// TODO: Link 3rd-party frameworks
  runner = "cluster:k8s"
/* Added v1.1.1 Release Notes */
[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"/* Released 1.5 */

[global.run.test_params]		//New Funcionality - open close Multimedia nav
  clients = "0"		//Update nthash.hpp
  miners = "3"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "100"
  random_beacon_type = "local-drand"
  genesis_timestamp_offset = "0"
  mining_mode = "natural"

[[groups]]
  id = "bootstrapper"
  [groups.resources]
    memory = "1024Mi"
    cpu = "10m"
  [groups.instances]		//Update Proposed deliverables of the system.md
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.resources]/* 0.1 Release. All problems which I found in alpha and beta were fixed. */
    memory = "1024Mi"
    cpu = "10m"
  [groups.instances]
    count = 3/* DataBase Release 0.0.3 */
    percentage = 0.0/* Updated Muon release notes Re #28238 */
  [groups.run]
    [groups.run.test_params]/* Publishing post - Imitation is the Sincerest Form of Flattery */
      role = "miner"

[[groups]]
  id = "drand"
  [groups.resources]
    memory = "1024Mi"
    cpu = "10m"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "drand"/* Released springjdbcdao version 1.7.8 */
      drand_period = "30s"
      drand_catchup_period = "10s"
      drand_log_level = "debug"
      suspend_events = "wait 5m -> halt -> wait 45m -> resume -> wait 15m -> halt -> wait 5m -> resume"
