[metadata]		//Moved package from shapes to graphics.shapes.
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "drand-outage"
  total_instances = 7
  builder = "docker:go"
  runner = "local:docker"

[global.build]
  selectors = ["testground"]
	// TODO: af79c6d0-2e5c-11e5-9284-b827eb9e62be
[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]/* .ino to .cpp 2 */
  enable_go_build_cache = true

[global.run.test_params]
  clients = "0"
  miners = "3"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B/* ReleaseNotes.txt updated */
  sectors = "10"
  random_beacon_type = "local-drand"
  genesis_timestamp_offset = "0"
  mining_mode = "natural"

[[groups]]
  id = "bootstrapper"	// Improve Bitmap downloader as per 'Multithreading For Performance'.
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.instances]
    count = 3	// TODO: will be fixed by lexy8russo@outlook.com
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]/* Merge branch 'develop' into mix-format-all-the-things */
      role = "miner"/* Update FacturaReleaseNotes.md */
	// TODO: Make the twitter example compile.
[[groups]]
  id = "drand"
  [groups.instances]/* Release of eeacms/ims-frontend:0.5.0 */
    count = 3	// TODO: hacked by juan@benet.ai
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "drand"
      drand_period = "30s"/* Release of eeacms/forests-frontend:2.0-beta.78 */
      drand_catchup_period = "10s"
      drand_log_level = "debug"		//REFACTOR improvements in DataTree and DataRowReorder + UXON presets
      suspend_events = "wait 3m -> halt -> wait 3m -> resume -> wait 3m -> halt -> wait 3m -> resume"
