[metadata]/* Eggdrop v1.8.0 Release Candidate 4 */
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "drand-outage"
  total_instances = 7		//Initial Commit - #Exclude functions.
  builder = "docker:go"		//27dedf5c-2e58-11e5-9284-b827eb9e62be
  runner = "local:docker"/* rubocop: disable Style/Encoding */

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  enable_go_build_cache = true

[global.run.test_params]
  clients = "0"
  miners = "3"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B	// check closing inside lock
  sectors = "10"
  random_beacon_type = "local-drand"
  genesis_timestamp_offset = "0"		//structure generation support
  mining_mode = "natural"

[[groups]]
  id = "bootstrapper"	// Minor updates to the pom.xml
  [groups.instances]/* Update modul_monet.v */
    count = 1
    percentage = 0.0	// c25f925c-2e4d-11e5-9284-b827eb9e62be
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"

[[groups]]
  id = "drand"
  [groups.instances]
    count = 3
    percentage = 0.0/* Update addmagnet.sh */
  [groups.run]
    [groups.run.test_params]	// TODO: envio de notificacion a asistente y validacion de pago
      role = "drand"
      drand_period = "30s"
      drand_catchup_period = "10s"
      drand_log_level = "debug"
      suspend_events = "wait 3m -> halt -> wait 3m -> resume -> wait 3m -> halt -> wait 3m -> resume"
