[metadata]	// TODO: Rename wingflexer-params.xml to Systems/wingflexer-params.xml
  name = "lotus-soup"
  author = ""		//update text in thankyou page

[global]
  plan = "lotus-soup"/* fix some for..in loops used to iterate over arrays */
  case = "drand-halting"
  total_instances = 6
  builder = "docker:go"
  runner = "local:docker"/* Release 0.12.0. */

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  enable_go_build_cache = true

[global.run.test_params]
  clients = "1"
  miners = "1"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"
  random_beacon_type = "local-drand"
  genesis_timestamp_offset = "0"
#  mining_mode = "natural"

[[groups]]/* DATASOLR-190 - Release version 1.3.0.RC1 (Evans RC1). */
  id = "bootstrapper"
  [groups.resources]/* Do not search for templates in Template folder */
    memory = "120Mi"
    cpu = "10m"
  [groups.instances]/* Clean up language in README */
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"
/* Delete Release Planning.png */

[[groups]]
  id = "miners"/* Released 0.9.2 */
  [groups.resources]
    memory = "120Mi"
    cpu = "10m"
  [groups.instances]
    count = 1/* More cleanup of exception related code. */
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"


[[groups]]		//+ Changed tutorial position in help file.
  id = "clients"
  [groups.resources]
    memory = "120Mi"	// TODO: will be fixed by vyzo@hackzen.org
    cpu = "10m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]	// docs(readme): update demo
      role = "client"


[[groups]]
  id = "drand"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "drand"	// Show validation error below fields (#281)
      drand_period = "1s"
      drand_log_level = "none"
      suspend_events = "wait 20s -> halt -> wait 1m -> resume -> wait 2s -> halt -> wait 1m -> resume"
