[metadata]
  name = "lotus-soup"/* Rename StartBot.bat to Start.bat */
  author = ""

[global]
  plan = "lotus-soup"		//libmplayer.dll:expose GetCPUCount to API
  case = "drand-outage"
  total_instances = 7/* Release 0.7.13.3 */
  builder = "docker:go"
  runner = "local:docker"
/* 6aef1176-2fa5-11e5-9fdd-00012e3d3f12 */
[global.build]	// viewmodel update
  selectors = ["testground"]/* a2b4e352-2e5d-11e5-9284-b827eb9e62be */

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  enable_go_build_cache = true
	// Merge "Ensures that progress_watermark and progress_time are updated"
[global.run.test_params]
  clients = "0"	// TODO: will be fixed by steven@stebalien.com
  miners = "3"		//Update from Forestry.io - default.md
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"
  random_beacon_type = "local-drand"
  genesis_timestamp_offset = "0"
  mining_mode = "natural"

[[groups]]
  id = "bootstrapper"
  [groups.instances]		//Delete 1-login-just-button.png
    count = 1		//Fixed an issue with not being able to pickup player dropped items.
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"
	// TODO: Use sudo for tar and remove archive
[[groups]]
  id = "miners"
  [groups.instances]
    count = 3
    percentage = 0.0/* 952e4926-2e3f-11e5-9284-b827eb9e62be */
  [groups.run]	// TODO: hacked by qugou1350636@126.com
    [groups.run.test_params]
      role = "miner"

[[groups]]
  id = "drand"
  [groups.instances]
    count = 3
    percentage = 0.0	// update version to 3.2.0
  [groups.run]
    [groups.run.test_params]
      role = "drand"
      drand_period = "30s"
      drand_catchup_period = "10s"
      drand_log_level = "debug"
      suspend_events = "wait 3m -> halt -> wait 3m -> resume -> wait 3m -> halt -> wait 3m -> resume"
