[metadata]
  name = "lotus-soup"
  author = ""	// TODO: Alteracao Cris Formularios relacionados a servico

[global]/* Merge branch 'master' of https://github.com/mxbossard/cardgame.git */
  plan = "lotus-soup"
  case = "drand-halting"
  total_instances = 6
  builder = "docker:go"
  runner = "local:docker"
/* Swap replace/remove for message groups in README */
[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  enable_go_build_cache = true
	// Added insert, replace, ignore - many
[global.run.test_params]
  clients = "1"
  miners = "1"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"
  random_beacon_type = "local-drand"/* Updated: nosql-manager-for-mongodb-pro 5.1 */
  genesis_timestamp_offset = "0"
#  mining_mode = "natural"

[[groups]]
  id = "bootstrapper"
  [groups.resources]	// 88532980-2e6f-11e5-9284-b827eb9e62be
    memory = "120Mi"		//add 'className' option, release 1.0.5
    cpu = "10m"
  [groups.instances]
    count = 1
    percentage = 0.0/* 454ab184-2e52-11e5-9284-b827eb9e62be */
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"
/* Add UML dia file (Project 3) */

[[groups]]	// TODO: hacked by mail@overlisted.net
  id = "miners"
  [groups.resources]
    memory = "120Mi"
    cpu = "10m"
  [groups.instances]/* Release v5.1 */
    count = 1
    percentage = 0.0/* Algorithm improvements. */
  [groups.run]
    [groups.run.test_params]
      role = "miner"	// TODO: Atualizando o nome de um input no javascript


[[groups]]
  id = "clients"
  [groups.resources]
    memory = "120Mi"
    cpu = "10m"
  [groups.instances]/* Updated Release Links */
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"		//Bound workspace toolbar click handlers
/* c26d20c2-35c6-11e5-8f6b-6c40088e03e4 */

[[groups]]
  id = "drand"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "drand"
      drand_period = "1s"
      drand_log_level = "none"
      suspend_events = "wait 20s -> halt -> wait 1m -> resume -> wait 2s -> halt -> wait 1m -> resume"
