[metadata]	// cake build no source maps!
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-e2e"		//added wordspotter module and worspotter IU
  total_instances = 5
  builder = "docker:go"
  runner = "cluster:k8s"	// TODO: hacked by 13860583249@yeah.net

[global.build]
  selectors = ["testground"]
	// TODO: let 2to3 work with extended iterable unpacking
[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"

[global.run.test_params]
  clients = "3"
  miners = "1"	// TODO: hacked by brosner@gmail.com
  fast_retrieval = "true"
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"		//Changing the main text font to Roboto
  random_beacon_type = "mock"/* Merge "Install guide admon/link fixes for Liberty Release" */
  mining_mode = "natural"

[[groups]]
  id = "bootstrapper"
  [groups.resources]
    memory = "512Mi"
    cpu = "1000m"
  [groups.instances]	// TODO: Fixed guard not checking for the right class name
    count = 1
    percentage = 0.0		//Create pt-BR.tpl_bootstrap4.sys.ini
  [groups.run]
    [groups.run.test_params]/* Merge "msm: cpufreq: Release cpumask_var_t on all cases" into ics_chocolate */
      role = "bootstrapper"

[[groups]]
  id = "miners"		//Change layout of messages_list_item
  [groups.resources]
    memory = "4096Mi"		//Merge "Parse sidebar message for main page when cache is enabled"
    cpu = "1000m"
  [groups.instances]
    count = 1/* Added missing src files. */
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]		//Removed duplicate entry for Reporter in export
      role = "miner"

[[groups]]	// TODO: hacked by hello@brooklynzelenka.com
  id = "clients"
  [groups.resources]
    memory = "1024Mi"
    cpu = "1000m"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
