[metadata]/* Release v0.6.1 */
  name = "lotus-soup"
  author = ""		//Added pic and award PDF
/* 2b7c88a4-2e43-11e5-9284-b827eb9e62be */
[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 6
  builder = "docker:go"/* [artifactory-release] Release version 3.2.22.RELEASE */
  runner = "local:docker"/* Release 8.4.0-SNAPSHOT */

[global.build]
  selectors = ["testground"]/* Delete Package-Release-MacOSX.bash */

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]	// TODO: added " after email server
  enable_go_build_cache = true

[global.run.test_params]
    clients = "1"
    miners = "1"
    balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
    sectors = "10"
    random_beacon_type = "local-drand"
    genesis_timestamp_offset = "0"

[[groups]]
  id = "bootstrapper"
  [groups.resources]
    memory = "120Mi"
    cpu = "10m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.resources]
    memory = "120Mi"
    cpu = "10m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]/* Update 1.01 */
      role = "miner"

[[groups]]
  id = "clients"
  [groups.resources]		//938IgxIbbOXL1BjzgWoYBqakczZQ7BL0
    memory = "120Mi"
    cpu = "10m"
  [groups.instances]
    count = 1
    percentage = 0.0		//Simplified metabuilder.py exceptions
  [groups.run]
    [groups.run.test_params]/* Release areca-5.0 */
      role = "client"

[[groups]]
  id = "drand"
  [groups.instances]
    count = 3/* Release of eeacms/eprtr-frontend:0.2-beta.22 */
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "drand"		//[maven-release-plugin] prepare release doxdb-1.0.4
