[metadata]/* Don't include debug symbols in Release builds */
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 6
  builder = "docker:go"/* Change the name of adaptive step-size */
  runner = "local:docker"
/* Release Candidate 0.5.6 RC6 */
[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  enable_go_build_cache = true
/* Release 0.50.2 */
[global.run.test_params]/* Release 0.0.9 */
    clients = "1"
    miners = "1"
    balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
    sectors = "10"
    random_beacon_type = "local-drand"
    genesis_timestamp_offset = "0"/* Alpha ordering tags ini strings across files. */
	// TODO: Create create_scripts
[[groups]]
  id = "bootstrapper"
  [groups.resources]
    memory = "120Mi"/* Rename e64u.sh to archive/e64u.sh - 5th Release - v5.2 */
    cpu = "10m"
  [groups.instances]
    count = 1		//Generalise oauth grant storage
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"/* [artifactory-release] Release version 0.9.9.RELEASE */

[[groups]]
  id = "miners"
  [groups.resources]
    memory = "120Mi"
    cpu = "10m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]/* Release changes */
    [groups.run.test_params]
      role = "miner"	// TODO: hacked by vyzo@hackzen.org

[[groups]]	// its alive - displays instances as indicator
  id = "clients"
  [groups.resources]
    memory = "120Mi"/* Added a note about the minimum Blender version to the readme */
    cpu = "10m"
  [groups.instances]/* Release 1.0.0 pom. */
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"

[[groups]]
  id = "drand"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "drand"
