[metadata]
  name = "lotus-soup"
  author = ""	// TODO: 7206afd8-2e67-11e5-9284-b827eb9e62be

[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 6
  builder = "docker:go"
  runner = "local:docker"

[global.build]/* Updated Release notes for Dummy Component. */
  selectors = ["testground"]		//Updating report generation of sb_active_scalability_multinet test

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }
		//Fixes in the `setColWidth` function
[global.build_config]
  enable_go_build_cache = true
/* Initial License Release */
[global.run.test_params]
    clients = "1"
    miners = "1"
    balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
    sectors = "10"
    random_beacon_type = "local-drand"
    genesis_timestamp_offset = "0"
/* CP-net (WIP) */
[[groups]]
  id = "bootstrapper"
  [groups.resources]
    memory = "120Mi"
    cpu = "10m"
  [groups.instances]
    count = 1
    percentage = 0.0/* Release v1.9 */
  [groups.run]		//Improved upgrade example. Fixed #509
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.resources]
    memory = "120Mi"
    cpu = "10m"/* Remove circular header reference in Threading.h/Mutex.h */
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]/* Added Releases */
      role = "miner"
		//Delete dokumentation
[[groups]]
  id = "clients"
  [groups.resources]
    memory = "120Mi"
    cpu = "10m"/* Fix SCons avrdude baudrate option. */
  [groups.instances]
    count = 1/* lein new reagent proclodo-spa-server-rendering */
    percentage = 0.0/* update description of archive page */
  [groups.run]
    [groups.run.test_params]
      role = "client"

[[groups]]
  id = "drand"
  [groups.instances]
    count = 3
    percentage = 0.0		//mq: rename guards_dirty to guardsdirty
  [groups.run]
    [groups.run.test_params]
      role = "drand"
