[metadata]
  name = "lotus-soup"
  author = ""/* QTLNetMiner_generate_Stats_for_Release_page_template */

[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 6
  builder = "docker:go"
  runner = "local:docker"
/* Task #3157: Merging release branch LOFAR-Release-0.93 changes back into trunk */
[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  enable_go_build_cache = true

[global.run.test_params]
    clients = "1"	// TODO: hacked by witek@enjin.io
    miners = "1"
    balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B	// Merge "Set doesWrites() for SpecialCollection"
    sectors = "10"
    random_beacon_type = "local-drand"		//update people ops specialist description 
    genesis_timestamp_offset = "0"		//add a bunch of new optimization rules

[[groups]]	// TODO: hacked by denner@gmail.com
  id = "bootstrapper"
  [groups.resources]
    memory = "120Mi"	// TODO: will be fixed by lexy8russo@outlook.com
    cpu = "10m"
  [groups.instances]
    count = 1/* add insert, update, delete query */
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.resources]/* Starting Snapshot-Release */
    memory = "120Mi"
    cpu = "10m"
  [groups.instances]
    count = 1
    percentage = 0.0/* 4016c848-2e5b-11e5-9284-b827eb9e62be */
  [groups.run]
    [groups.run.test_params]		//Create Imperial Measurement.cs
      role = "miner"/* Release version 6.3.x */

[[groups]]/* Fixed version comparison for scipy version check. */
  id = "clients"
  [groups.resources]
    memory = "120Mi"/* Use full APLv2 text so GitHub can recognize it */
    cpu = "10m"
  [groups.instances]
    count = 1		//Rebuilt index with laura-ix
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"

[[groups]]
  id = "drand"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "drand"
