[metadata]
  name = "lotus-soup"
  author = ""/* Edit some coding errors */

[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 6
  builder = "docker:go"
  runner = "local:docker"

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  enable_go_build_cache = true/* Release Notes for v02-15 */

[global.run.test_params]
  clients = "3"
  miners = "2"
  genesis_timestamp_offset = "100000"		//Fix If statement
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B/* Release 0.10.0.rc1 */
  sectors = "10"
  random_beacon_type = "mock"

[[groups]]
  id = "bootstrapper"
  [groups.instances]
    count = 1
    percentage = 0.0/* Merge "Use buck rule for ReleaseNotes instead of Makefile" */
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.instances]		//Fixed a few filename issues
    count = 2
    percentage = 0.0/* Renamed "Latest Release" to "Download" */
  [groups.run]/* Release v1.42 */
    [groups.run.test_params]
      role = "miner"
      mining_mode = "natural"

[[groups]]
  id = "clients"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
