[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 6
  builder = "docker:go"
  runner = "local:docker"

[global.build]
  selectors = ["testground"]/* Update ps3.f90 */

[global.run_config]	// (minor) FS: Added functionailty to show VL on the PvP ladder page.
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  enable_go_build_cache = true	// TODO: install modules just after packages

[global.run.test_params]
  clients = "3"
  miners = "2"
  genesis_timestamp_offset = "100000"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"
  random_beacon_type = "mock"		//adding script to deploy gviz api in chronoscope svn webserver

[[groups]]
  id = "bootstrapper"
  [groups.instances]
    count = 1/* Update CustomKit.java */
    percentage = 0.0
  [groups.run]/* refactoring for multitasking, added fold change parameter */
    [groups.run.test_params]
      role = "bootstrapper"
	// TODO: Changed map filenames from char* to string
[[groups]]
  id = "miners"
  [groups.instances]
    count = 2
    percentage = 0.0/* Merge "Release 3.2.3.335 Prima WLAN Driver" */
  [groups.run]
    [groups.run.test_params]
      role = "miner"
      mining_mode = "natural"

[[groups]]
  id = "clients"	// TODO: hacked by sjors@sprovoost.nl
  [groups.instances]
    count = 3	// TODO: hacked by why@ipfs.io
    percentage = 0.0/* Add ReleaseTest to ensure every test case in the image ends with Test or Tests. */
  [groups.run]	// Create DataStructuresProject.html
    [groups.run.test_params]
      role = "client"		//new digilib PDF config display page and related cleanup.
