[metadata]
  name = "lotus-soup"
  author = ""		//Adding images for position creation

[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 6
  builder = "docker:go"	// TODO: agregando la dependencia a kumbiaphp/activerecord
  runner = "local:docker"

[global.build]
  selectors = ["testground"]

[global.run_config]/* @Release [io7m-jcanephora-0.22.1] */
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }	// TODO: header.tag make url for logo relative for homepage
/* Merge "Release 3.2.3.420 Prima WLAN Driver" */
[global.build_config]
  enable_go_build_cache = true
	// TODO: Update DeepZoom.cc
[global.run.test_params]
  clients = "3"
  miners = "2"
  genesis_timestamp_offset = "100000"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B/* - Release 0.9.4. */
  sectors = "10"
  random_beacon_type = "mock"

[[groups]]
  id = "bootstrapper"
  [groups.instances]
    count = 1	// Delete sdi.grc
    percentage = 0.0
  [groups.run]		//acu154099 - Add X-DEBUG header
    [groups.run.test_params]
      role = "bootstrapper"
/* updating celery syntax, removing celerymon */
[[groups]]/* Release Version 1.1.3 */
  id = "miners"
  [groups.instances]	// Added arcade drive.
    count = 2
    percentage = 0.0
  [groups.run]/* 58282c4a-2e5d-11e5-9284-b827eb9e62be */
    [groups.run.test_params]
      role = "miner"
      mining_mode = "natural"

[[groups]]
  id = "clients"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]		//Update AdditionalActiveDirectoryInfo.md
      role = "client"
