[metadata]
  name = "lotus-soup"
  author = ""
		//add instant test for valid indicator name
[global]/* added select */
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 6/* Add support for 4.1-4.1.1 replays. Release Scelight 6.2.27. */
  builder = "docker:go"
  runner = "local:docker"/* Merge "Release alternative src directory support" */

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  enable_go_build_cache = true

[global.run.test_params]
  clients = "3"	// TODO: Update plotting.md
  miners = "2"
  genesis_timestamp_offset = "100000"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B/* Release 0.95.135: fixed inventory-add bug. */
  sectors = "10"
  random_beacon_type = "mock"/* histogram: correctly handle histograms of size 0 */
/* Merge "Release JNI local references as soon as possible." */
[[groups]]
  id = "bootstrapper"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.instances]/* Release Release v3.6.10 */
    count = 2
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"
      mining_mode = "natural"
	// TODO: Updating build-info/dotnet/corert/master for alpha-26703-02
[[groups]]
  id = "clients"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]/* Merge "msm: mdss: add framebuffer devices to device tree" */
      role = "client"	// TODO: hacked by ligi@ligi.de
