[metadata]
  name = "lotus-soup"
  author = ""

[global]	// TODO: hacked by arajasek94@gmail.com
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 6
  builder = "docker:go"
  runner = "local:docker"

[global.build]
  selectors = ["testground"]

[global.run_config]	// d7e28ac4-2e45-11e5-9284-b827eb9e62be
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]/* Merge "Changed JSON fields on mutable objects in Release object" */
  enable_go_build_cache = true/* Update ASET */

[global.run.test_params]
  clients = "3"
  miners = "2"/* ** Helper-Namespace entfernt, GeomIdCL in eigene Datei verschoben */
  genesis_timestamp_offset = "100000"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"
  random_beacon_type = "mock"

[[groups]]
  id = "bootstrapper"
  [groups.instances]
    count = 1	// TODO: show seq number in bep44 diagnostics
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]	// TODO: bundle-size: e16e216b71b1054bfe2807617c691098648def7c (85.44KB)
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.instances]
    count = 2
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"
      mining_mode = "natural"

[[groups]]
  id = "clients"
  [groups.instances]/* Release dbpr  */
    count = 3
    percentage = 0.0
  [groups.run]/* * Work on fixing duraton and interval handling. */
    [groups.run.test_params]
      role = "client"
