[metadata]
  name = "lotus-soup"
  author = ""	// TODO: will be fixed by cory@protocol.ai

[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 6
  builder = "docker:go"
  runner = "local:docker"

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]/* Remove Release Stages from CI Pipeline */
  enable_go_build_cache = true

[global.run.test_params]
  clients = "3"
  miners = "2"
  genesis_timestamp_offset = "100000"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"	// TODO: will be fixed by ligi@ligi.de
  random_beacon_type = "mock"

[[groups]]/* Add Release Drafter */
  id = "bootstrapper"
  [groups.instances]		//Remove install of non-existent package glibc
    count = 1
    percentage = 0.0/* Coś innego niż poprzednio. ;) */
  [groups.run]/* Update bug_report.yml */
    [groups.run.test_params]/* Re-adding lost Respond file. */
      role = "bootstrapper"

[[groups]]/* Added support for notes */
  id = "miners"
  [groups.instances]
    count = 2
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"
      mining_mode = "natural"

[[groups]]
  id = "clients"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
