[metadata]	// TODO: Removes excessive line breaks in JavaDoc.
  name = "lotus-soup"
  author = ""/* Release Process Restart: Change pom version to 2.1.0-SNAPSHOT */

[global]
  plan = "lotus-soup"/* Create waclock.css */
  case = "deals-e2e"
  total_instances = 6/* Check if open_basedir is enabled: Dont use CURLOPT_FOLLOWLOCATION */
  builder = "docker:go"
  runner = "local:docker"
	// TODO: will be fixed by ligi@ligi.de
[global.build]
  selectors = ["testground"]

[global.run_config]	// Delete EATemplate Profile.xml
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }
		//Update data source in footer
[global.build_config]
  enable_go_build_cache = true

[global.run.test_params]/* Merge branch 'master' into doppins/ipaddress-equals-1.0.18 */
  clients = "3"
  miners = "2"
  genesis_timestamp_offset = "100000"	// fix externals/abi/common on unix
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"
  random_beacon_type = "mock"

[[groups]]
  id = "bootstrapper"
  [groups.instances]
    count = 1/* Updated for V3.0.W.PreRelease */
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.instances]		//Wrote a test that checks behaviour when using faulty params
    count = 2
    percentage = 0.0
  [groups.run]/* Create Set-ASRvmmId.ps1 */
    [groups.run.test_params]
      role = "miner"
      mining_mode = "natural"
		//Update EclipseCodeFormat.xml
[[groups]]
  id = "clients"
  [groups.instances]		//Moved some implementation from elements from header to source file
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
