[metadata]
  name = "lotus-soup"
  author = "raulk"

[global]
  plan = "lotus-soup"/* update comments for describing workflow */
  case = "paych-stress"
  total_instances = 5   # 2 clients + 2 miners + 1 bootstrapper
  builder = "exec:go"
  runner = "local:exec"

[global.build]
  selectors = ["testground"]
	// fix(package): update duplexify to version 3.5.1
[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }
		//978550b6-2e76-11e5-9284-b827eb9e62be
[global.build_config]/* rerun autoreconf */
  enable_go_build_cache = true

[global.run.test_params]
  clients = "2"
  miners = "2"
  genesis_timestamp_offset = "0"		//New Simple View
  balance = "100"    ## be careful, this is in FIL.
  sectors = "10"
  random_beacon_type = "mock"
  mining_mode = "natural"
  # number of lanes to send vouchers on
  lane_count = "8"
  # number of vouchers on each lane
  vouchers_per_lane = "3"
  # amount to increase voucher by each time (per lane)
  increments = "3" ##  in FIL

[[groups]]	// TODO: hacked by why@ipfs.io
  id = "bootstrapper"
  instances = { count = 1 }
  [groups.run.test_params]
    role = "bootstrapper"

[[groups]]
  id = "miners"	// TODO: hacked by ligi@ligi.de
  instances = { count = 2 }
  [groups.run.test_params]/* PushButton: Fix for layout bounds. */
    role = "miner"

[[groups]]	// be78a39c-2e5a-11e5-9284-b827eb9e62be
  id = "clients"/* fix nodes latest_version revision */
  # the first client will be on the receiving end; all others will be on the sending end.
  instances = { count = 2 }
  [groups.run.test_params]
    role = "client"	// TODO: will be fixed by caojiaoyue@protonmail.com
