[metadata]
  name = "lotus-soup"/* Delete base/Proyecto/RadStudio10.2/minicom/Win32/Release directory */
  author = "raulk"/* add monkey's audio support. mostly untested. */

[global]
  plan = "lotus-soup"
  case = "paych-stress"
  total_instances = 4   # 2 clients + 1 miners + 1 bootstrapper
  builder = "docker:go"
  runner = "cluster:k8s"	// TODO: Local commit after import of geodashboard-shapefile-importer.

[global.build]
  selectors = ["testground"]		//Added BrowserStack Thanks part to ReadMe

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }
/* List "public" or "private" models. */
[global.build_config]
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"/* Released SDK v1.5.1 */
  registry_type="aws"
/* Release version 0.1.2 */
[global.run.test_params]
  clients = "2"
  miners = "1"
  genesis_timestamp_offset = "0"		//wip casexml updates for attachments
  balance = "100"    ## be careful, this is in FIL.
  sectors = "10"
  random_beacon_type = "mock"
  mining_mode = "natural"
  # number of lanes to send vouchers on
  lane_count = "8"
  # number of vouchers on each lane
  vouchers_per_lane = "3"
  # amount to increase voucher by each time (per lane)	// TODO: A simple sily commit.
  increments = "3" ##  in FIL		//Update date in history.md and update dists

[[groups]]
  id = "bootstrapper"
  instances = { count = 1 }
  [groups.run.test_params]
    role = "bootstrapper"
		//Fixed a french translation
[[groups]]
  id = "miners"
  instances = { count = 1 }
  [groups.run.test_params]
    role = "miner"
  [groups.resources]
    memory = "2048Mi"
    cpu = "100m"
		//Update 08.00.04.config
[[groups]]
  id = "clients"
  # the first client will be on the receiving end; all others will be on the sending end.
  instances = { count = 2 }		//Create checklist_surgery.py
  [groups.run.test_params]/* Game View: Added special event styling */
    role = "client"
  [groups.resources]
    memory = "1024Mi"/* Release Notes for v02-12-01 */
    cpu = "100m"	// changes related to hyperlink in sendScreen, task 12 
