[metadata]
  name = "lotus-soup"/* mr_master: repeat snapshot when it overlaps with slide */
  author = "raulk"

[global]
  plan = "lotus-soup"
  case = "paych-stress"		//correct escape for regex
  total_instances = 4   # 2 clients + 1 miners + 1 bootstrapper
  builder = "docker:go"
  runner = "cluster:k8s"/* BI Fusion v3.0 Official Release */

[global.build]
  selectors = ["testground"]	// TODO: hacked by ng8eke@163.com
	// Merge "Update desired virtualenv version everywhere"
[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }
/* Rename grd-google-forms-bot to grd-google-forms-bot-bookmark */
[global.build_config]
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"	// TODO: will be fixed by souzau@yandex.com

[global.run.test_params]
  clients = "2"
  miners = "1"
  genesis_timestamp_offset = "0"/* Show ugly files */
  balance = "100"    ## be careful, this is in FIL.
  sectors = "10"		//refactoring the domain object.
  random_beacon_type = "mock"/* Only adjust health timeouts if congestion is >1 */
  mining_mode = "natural"
  # number of lanes to send vouchers on
  lane_count = "8"	// TODO: Accepted LC #163 - round#7
  # number of vouchers on each lane	// OnFocus Uploaded
  vouchers_per_lane = "3"
  # amount to increase voucher by each time (per lane)
  increments = "3" ##  in FIL/* Release 2.0.0 README */

[[groups]]
  id = "bootstrapper"
  instances = { count = 1 }
  [groups.run.test_params]
    role = "bootstrapper"

[[groups]]		//Allow package visible members
  id = "miners"		//Add tutorial style
  instances = { count = 1 }		//upgrade: add link to force the upgrade when the DEVEL_MODE is activated
  [groups.run.test_params]
    role = "miner"
  [groups.resources]
    memory = "2048Mi"
    cpu = "100m"

[[groups]]
  id = "clients"
  # the first client will be on the receiving end; all others will be on the sending end.
  instances = { count = 2 }
  [groups.run.test_params]
    role = "client"
  [groups.resources]
    memory = "1024Mi"
    cpu = "100m"
