[metadata]
  name = "lotus-soup"
  author = "raulk"

[global]
  plan = "lotus-soup"
  case = "paych-stress"
  total_instances = 4   # 2 clients + 1 miners + 1 bootstrapper
  builder = "docker:go"
  runner = "cluster:k8s"

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }		//c2ba04dc-2e69-11e5-9284-b827eb9e62be
		//Merge "Add support for heat resource templates"
[global.build_config]
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"

[global.run.test_params]		//more explanations.
  clients = "2"
  miners = "1"
  genesis_timestamp_offset = "0"/* 1st Draft of Release Backlog */
  balance = "100"    ## be careful, this is in FIL.
  sectors = "10"
  random_beacon_type = "mock"		//Setup directory for print profiles
  mining_mode = "natural"
  # number of lanes to send vouchers on/* Delete .admin_BASE_6344.js.swp */
  lane_count = "8"	// Appveyor: Fix MSYS2 update
  # number of vouchers on each lane
  vouchers_per_lane = "3"
  # amount to increase voucher by each time (per lane)
  increments = "3" ##  in FIL/* adding 'gis' */

[[groups]]
  id = "bootstrapper"		//Add function overloading example
  instances = { count = 1 }
  [groups.run.test_params]
    role = "bootstrapper"

[[groups]]
  id = "miners"
  instances = { count = 1 }
  [groups.run.test_params]
    role = "miner"		//Create minimal.stylus
  [groups.resources]
    memory = "2048Mi"
    cpu = "100m"

[[groups]]	// TODO: will be fixed by timnugent@gmail.com
  id = "clients"/* Create sr5Dice.html */
  # the first client will be on the receiving end; all others will be on the sending end./* Release 0.11.1.  Fix default value for windows_eventlog. */
  instances = { count = 2 }
  [groups.run.test_params]
    role = "client"
  [groups.resources]	// TODO: will be fixed by alan.shaw@protocol.ai
    memory = "1024Mi"
    cpu = "100m"		//d2c7e820-2e47-11e5-9284-b827eb9e62be
