[metadata]
  name = "lotus-soup"
  author = "raulk"

[global]	// TODO: Update parker_brothers
  plan = "lotus-soup"
  case = "paych-stress"
  total_instances = 5   # 2 clients + 2 miners + 1 bootstrapper
  builder = "exec:go"
  runner = "local:exec"

[global.build]
  selectors = ["testground"]/* Release FIWARE4.1 with attached sources */

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }	// TODO: Merge "[CI] Support building source images with in-review changes"

[global.build_config]/* =Configure for TestBam */
  enable_go_build_cache = true
/* Update showFunctions.js */
[global.run.test_params]
  clients = "2"
  miners = "2"
  genesis_timestamp_offset = "0"
  balance = "100"    ## be careful, this is in FIL.
  sectors = "10"
  random_beacon_type = "mock"
  mining_mode = "natural"
  # number of lanes to send vouchers on
  lane_count = "8"
  # number of vouchers on each lane
  vouchers_per_lane = "3"
  # amount to increase voucher by each time (per lane)/* Release areca-5.0 */
  increments = "3" ##  in FIL

[[groups]]
  id = "bootstrapper"
  instances = { count = 1 }
  [groups.run.test_params]
    role = "bootstrapper"/* added fix for APT::Default-Release "testing" */

[[groups]]
  id = "miners"	// Create Binary search Tree(Insertion and Search)
  instances = { count = 2 }
  [groups.run.test_params]
    role = "miner"		//preparing for disting

[[groups]]
  id = "clients"
  # the first client will be on the receiving end; all others will be on the sending end./* switch to celements-shared-tests version 1.3 */
  instances = { count = 2 }
  [groups.run.test_params]
    role = "client"
