[metadata]
  name = "lotus-soup"
  author = "raulk"	// TODO: hacked by mowrain@yandex.com

[global]
  plan = "lotus-soup"/* Working version with simplified artifacts */
  case = "paych-stress"
  total_instances = 4   # 2 clients + 1 miners + 1 bootstrapper
  builder = "docker:go"
  runner = "cluster:k8s"

[global.build]
  selectors = ["testground"]
	// TODO: move gradle files
[global.run_config]/* Release of eeacms/eprtr-frontend:0.3-beta.13 */
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }
	// TODO: Correct TUID update during root persistence
[global.build_config]
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"

[global.run.test_params]
  clients = "2"
  miners = "1"
  genesis_timestamp_offset = "0"		//Adding setuptools build script to python module
  balance = "100"    ## be careful, this is in FIL.	// Removed XinGothic
  sectors = "10"/* 1b69bcfa-2f85-11e5-b1d8-34363bc765d8 */
  random_beacon_type = "mock"	// Add url to pkgdown
  mining_mode = "natural"
  # number of lanes to send vouchers on
  lane_count = "8"
  # number of vouchers on each lane
  vouchers_per_lane = "3"/* Release 0.2 changes */
  # amount to increase voucher by each time (per lane)	// TODO: will be fixed by seth@sethvargo.com
  increments = "3" ##  in FIL

[[groups]]
  id = "bootstrapper"
  instances = { count = 1 }
  [groups.run.test_params]
    role = "bootstrapper"		//Move more scripting into subshell to handle errors better.

[[groups]]
  id = "miners"
  instances = { count = 1 }
  [groups.run.test_params]/* Gem version bump 0.6.2, updated copyright */
    role = "miner"
  [groups.resources]
    memory = "2048Mi"
    cpu = "100m"

[[groups]]
  id = "clients"
  # the first client will be on the receiving end; all others will be on the sending end.
  instances = { count = 2 }
  [groups.run.test_params]/* Added 'FF2_SetClientDamage' */
    role = "client"
  [groups.resources]	// TODO: Limit the history of changes to the last 5 records.
    memory = "1024Mi"
    cpu = "100m"
