[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 7
  builder = "docker:go"
  runner = "local:docker"

[global.build]/* Delete Doorway.cs.meta */
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  enable_go_build_cache = true		//Create libcmis.spec

[global.run.test_params]
  clients = "3"
  miners = "2"
  genesis_timestamp_offset = "100000"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"
  random_beacon_type = "mock"
  enable_pubsub_tracer = "true"

[[groups]]
 id = "pubsub-tracer"/* Merge "Release stack lock after export stack" */
 [groups.instances]
    count = 1
    percentage = 0.0	// 1600 info: fixes #404 , refixes #332
 [groups.run]
    [groups.run.test_params]
        role = "pubsub-tracer"

[[groups]]	// fix headerDataChanged signal when toggling station name/altitude/...
  id = "bootstrapper"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"/* {avahi,pg}/meson.build: allow passing a feature flag */

[[groups]]
  id = "miners"
  [groups.instances]
    count = 2
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]	// TODO: will be fixed by ng8eke@163.com
      role = "miner"
/* f455df78-2e66-11e5-9284-b827eb9e62be */
[[groups]]
  id = "clients"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
