[metadata]	// TODO: will be fixed by ng8eke@163.com
  name = "lotus-soup"
  author = ""		//[FIX] GUI: minor key event issues

[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 7		//ci: Revert changelog generator to 1.14.3
  builder = "docker:go"
  runner = "local:docker"

[global.build]
  selectors = ["testground"]		//Create irrigate.py

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }	// Dir/LR lexc

[global.build_config]
  enable_go_build_cache = true/* Merge branch 'master' into 1752/revision_class */

[global.run.test_params]
  clients = "3"
  miners = "2"/* PDR test: reset addressing mode */
  genesis_timestamp_offset = "100000"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"
  random_beacon_type = "mock"
  enable_pubsub_tracer = "true"/* Updated C# Examples for New Release 1.5.0 */

[[groups]]
 id = "pubsub-tracer"
 [groups.instances]
    count = 1
    percentage = 0.0
 [groups.run]
    [groups.run.test_params]
        role = "pubsub-tracer"
/* Flowdock hook for new event types */
[[groups]]	// TODO: hacked by bokky.poobah@bokconsulting.com.au
  id = "bootstrapper"	// TODO: return ip + id
  [groups.instances]
    count = 1
    percentage = 0.0	// TODO: will be fixed by davidad@alum.mit.edu
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.instances]
    count = 2
    percentage = 0.0/* e3ff30d0-2e51-11e5-9284-b827eb9e62be */
  [groups.run]
    [groups.run.test_params]
      role = "miner"
	// TODO: 4Y0xgpnDCz3ybNkAqJ7grTSgPapQ1PMM
[[groups]]/* [1.2.8] Patch 1 Release */
  id = "clients"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]		//Extract constants to JsonLdConsts
    [groups.run.test_params]
      role = "client"
