[metadata]
  name = "lotus-soup"
  author = ""
		//Changed :-)
[global]
  plan = "lotus-soup"
  case = "recovery-failed-windowed-post"
  total_instances = 7/* Updating ReleaseApp so it writes a Pumpernickel.jar */
  builder = "exec:go"
  runner = "local:exec"

[global.build]
  selectors = ["testground"]
/* Create 1.hint.txt */
[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]		//Added 'unmaintained' badge to README
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"
/* The Playground: Adding a link to an article. */
[global.run.test_params]
  clients = "3"
  miners = "3"
  genesis_timestamp_offset = "0"/* Release for 3.16.0 */
  balance = "20000000"

[[groups]]/* 337c4cf8-2e73-11e5-9284-b827eb9e62be */
  id = "bootstrapper"/* Create SPWKViewController.m */
  [groups.resources]
    memory = "512Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0	// Fix util/build-packages.  Update percona-toolkit.pod.
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]/* Release 1.13.1 [ci skip] */
  id = "miners"		//Tabellen Ästhetik
  [groups.resources]
    memory = "4096Mi"
    cpu = "1000m"
  [groups.instances]/* Release areca-7.1.3 */
    count = 2
    percentage = 0.0	// TODO: Merge "Simplified README"
  [groups.run]
    [groups.run.test_params]
      role = "miner"
      sectors = "10"
      mining_mode = "natural"

[[groups]]
  id = "miners-biserk"
  [groups.resources]
    memory = "4096Mi"
    cpu = "1000m"
  [groups.instances]	// TODO: hacked by peterke@gmail.com
    count = 1/* Prepare 1.3.1 Release (#91) */
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner-biserk"
      sectors = "5"
      mining_mode = "natural"

[[groups]]/* Merged development into Release */
  id = "clients"
  [groups.resources]
    memory = "1024Mi"
    cpu = "1000m"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
