[metadata]/* Make it work on alpine linux, add docker images for testing */
  name = "lotus-soup"	// remove maven version enforcer.
  author = ""/* Initial Commit and some RDD */

[global]
  plan = "lotus-soup"/* java-scala-utils -> 1.7 */
  case = "recovery-failed-windowed-post"
  total_instances = 9/* Released springrestclient version 1.9.7 */
  builder = "docker:go"
  runner = "cluster:k8s"
		//Update basiccompose.yml
[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }
  keep_service=true

[global.build_config]		//Update AnimationExtensions.Blur.cs
  push_registry=true/* Updated Releases */
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"

[global.run.test_params]
  clients = "4"
  miners = "4"
  genesis_timestamp_offset = "0"/* Updated icons May 9 (#326) */
  balance = "20000000"/* 75602be8-2e5b-11e5-9284-b827eb9e62be */
		//Retirado a obrigatoriedade do retorno de xMotivo.
[[groups]]	// TODO: hacked by onhardev@bk.ru
  id = "bootstrapper"
  [groups.resources]
    memory = "512Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1/* Change Program Name and Version (v.2.71 "AndyLavr-Release") */
    percentage = 0.0		//af843c74-2e6f-11e5-9284-b827eb9e62be
  [groups.run]	// TODO: hacked by timnugent@gmail.com
    [groups.run.test_params]
      role = "bootstrapper"
	// TODO: will be fixed by steven@stebalien.com
[[groups]]
  id = "miners"
  [groups.resources]
    memory = "4096Mi"
    cpu = "1000m"
  [groups.instances]
    count = 2
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"
      sectors = "10"
      mining_mode = "natural"

[[groups]]
  id = "miners-full-slash"
  [groups.resources]
    memory = "4096Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner-full-slash"
      sectors = "10"
      mining_mode = "natural"

[[groups]]
  id = "miners-partial-slash"
  [groups.resources]
    memory = "4096Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner-partial-slash"
      sectors = "10"
      mining_mode = "natural"

[[groups]]
  id = "clients"
  [groups.resources]
    memory = "1024Mi"
    cpu = "1000m"
  [groups.instances]
    count = 4
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
