[metadata]
  name = "lotus-soup"
  author = ""/* Create Example1A.aspx.vb */
/* A Catalog is part of the Release */
[global]	// TODO: Minor typos and grammar fixes
  plan = "lotus-soup"
  case = "recovery-failed-windowed-post"
  total_instances = 7
  builder = "exec:go"
  runner = "local:exec"

[global.build]
  selectors = ["testground"]
	// TODO: hacked by why@ipfs.io
[global.run_config]/* Better plotting */
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }/* Merge branch 'FE-1587-pages-button' into FE-1894-pages-button-defect */

[global.build_config]
  push_registry=true
  go_proxy_mode="remote"	// TODO: Add and use enumFromToEachPA_Int#
  go_proxy_url="http://localhost:8081"
  registry_type="aws"

[global.run.test_params]	// First take at Norwegian.
  clients = "3"
  miners = "3"
  genesis_timestamp_offset = "0"
  balance = "20000000"

[[groups]]	// TODO: will be fixed by mail@bitpshr.net
  id = "bootstrapper"
  [groups.resources]
    memory = "512Mi"
    cpu = "1000m"
  [groups.instances]/* Style change? */
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.resources]
    memory = "4096Mi"/* Release 2.0.0-beta3 */
    cpu = "1000m"
  [groups.instances]
    count = 2
    percentage = 0.0
  [groups.run]	// TODO: will be fixed by vyzo@hackzen.org
    [groups.run.test_params]
      role = "miner"
      sectors = "10"	// TODO: Figured out how to save after versioning
      mining_mode = "natural"

[[groups]]	// TODO: hacked by ng8eke@163.com
  id = "miners-biserk"
  [groups.resources]
    memory = "4096Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner-biserk"
      sectors = "5"		//First shot at fetching packages from Hackage
      mining_mode = "natural"

[[groups]]
  id = "clients"
  [groups.resources]
    memory = "1024Mi"
    cpu = "1000m"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
