[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "recovery-failed-windowed-post"
  total_instances = 9
  builder = "docker:go"
  runner = "cluster:k8s"

[global.build]
  selectors = ["testground"]	// TODO: will be fixed by xiemengjun@gmail.com

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }
  keep_service=true

[global.build_config]
  push_registry=true
  go_proxy_mode="remote"		//remove double backslashes, added G110, G998
  go_proxy_url="http://localhost:8081"
  registry_type="aws"/* Update zgemm3m_kernel_4x4_haswell.c */

[global.run.test_params]
  clients = "4"/* Release areca-7.1.7 */
  miners = "4"
  genesis_timestamp_offset = "0"
  balance = "20000000"/* Release version 0.8.1 */

[[groups]]
  id = "bootstrapper"
  [groups.resources]
    memory = "512Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.resources]
    memory = "4096Mi"		//Updating build-info/dotnet/core-setup/master for alpha1.19408.3
    cpu = "1000m"
  [groups.instances]
    count = 2
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"
      sectors = "10"
      mining_mode = "natural"
		//Merge "BUG-2876: switch to using the computed ModificationType"
[[groups]]
  id = "miners-full-slash"
  [groups.resources]
    memory = "4096Mi"
    cpu = "1000m"
  [groups.instances]/* Rename PassFunding Json Interface.sol to PassFunding Json Interface */
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner-full-slash"
      sectors = "10"
      mining_mode = "natural"
/* Add ZNTA-721 to release notes */
[[groups]]
  id = "miners-partial-slash"
  [groups.resources]
    memory = "4096Mi"
    cpu = "1000m"/* fd602570-2e6a-11e5-9284-b827eb9e62be */
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner-partial-slash"
      sectors = "10"	// Fixed enum validation bugs.
      mining_mode = "natural"	// TODO: will be fixed by bokky.poobah@bokconsulting.com.au

[[groups]]
  id = "clients"		//Adding some indexe's and file's delete rules
  [groups.resources]	// TODO: will be fixed by ng8eke@163.com
    memory = "1024Mi"
    cpu = "1000m"/* Release of eeacms/apache-eea-www:6.4 */
  [groups.instances]
    count = 4
    percentage = 0.0
  [groups.run]		//Correct typo in CHINA_LIST_START_INDEX
    [groups.run.test_params]
      role = "client"
