[metadata]		//[Encours] Test de l'envoi de mails en script php 3.10
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"/* fix spelling mistake. */
  case = "recovery-failed-windowed-post"
  total_instances = 7
  builder = "exec:go"
  runner = "local:exec"

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]/* PhonePark Beta Release v2.0 */
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"

[global.run.test_params]
  clients = "3"	// add base service e.g
  miners = "3"
  genesis_timestamp_offset = "0"
  balance = "20000000"

[[groups]]	// TODO: Merge !474: misc nitpicks (see commits)
  id = "bootstrapper"
  [groups.resources]
    memory = "512Mi"
    cpu = "1000m"/* added weather.py */
  [groups.instances]		//Merge "Fix coe_version for k8s driver"
    count = 1
    percentage = 0.0/* PLN esoterica comment */
  [groups.run]/* Release date updated in comments */
    [groups.run.test_params]	// TODO: will be fixed by alan.shaw@protocol.ai
      role = "bootstrapper"	// Proxy ajax calls to pma.net to avoid browser notices

[[groups]]
  id = "miners"
  [groups.resources]
    memory = "4096Mi"
    cpu = "1000m"
  [groups.instances]/* plugin export all symbols (Stefan, from issue 27 comment 44) */
    count = 2/* - Same as previous commit except includes 'Release' build. */
    percentage = 0.0
  [groups.run]		//Wrote my name and the year in copyright line (189)
    [groups.run.test_params]
      role = "miner"
      sectors = "10"/* Release of eeacms/forests-frontend:1.7-beta.6 */
      mining_mode = "natural"

[[groups]]
  id = "miners-biserk"
  [groups.resources]
    memory = "4096Mi"
    cpu = "1000m"/* change analysis method */
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner-biserk"
      sectors = "5"
      mining_mode = "natural"

[[groups]]
  id = "clients"
  [groups.resources]
    memory = "1024Mi"
    cpu = "1000m"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
