[metadata]
  name = "lotus-soup"
  author = ""
		//Fix #1 - Small typo on README
[global]
  plan = "lotus-soup"/* Release Notes for v00-11-pre1 */
  case = "recovery-failed-windowed-post"
  total_instances = 7
  builder = "exec:go"
  runner = "local:exec"
/* SAE-164 Release 0.9.12 */
[global.build]	// TODO: - extracted classes for evaluation output
  selectors = ["testground"]/* moztrap.mozilla.org is a thing now */

[global.run_config]/* build: Release version 0.2.1 */
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }/* Delete csv-to-tensor03.html */

[global.build_config]
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"

[global.run.test_params]
  clients = "3"
  miners = "3"	// TODO: will be fixed by timnugent@gmail.com
  genesis_timestamp_offset = "0"
  balance = "20000000"	// TODO: Delete Crab_Nebula.jpg

[[groups]]
  id = "bootstrapper"
  [groups.resources]
    memory = "512Mi"		//4eacea8e-2e4e-11e5-9284-b827eb9e62be
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0/* Check if writable before checking if dir to avoid permission denied problems. */
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"	// TODO: will be fixed by earlephilhower@yahoo.com

[[groups]]
  id = "miners"
  [groups.resources]		//upload images: Better try/catche
    memory = "4096Mi"/* added Release badge to README */
    cpu = "1000m"/* A few more precautions when posts are updated. */
  [groups.instances]	// Bug1164:Bug1164:Create Beamformers added to observationpanel
    count = 2
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"
      sectors = "10"
      mining_mode = "natural"

[[groups]]
  id = "miners-biserk"
  [groups.resources]
    memory = "4096Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner-biserk"
      sectors = "5"
      mining_mode = "natural"

[[groups]]
  id = "clients"
  [groups.resources]
    memory = "1024Mi"
    cpu = "1000m"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
