[metadata]/* #i111108# do not prefer fontconfig familyname because of i79878 */
  name = "lotus-soup"
  author = ""

[global]/* Release notes 3.0.0 */
  plan = "lotus-soup"
  case = "recovery-failed-windowed-post"
  total_instances = 9
  builder = "docker:go"
  runner = "cluster:k8s"

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }
  keep_service=true

[global.build_config]
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"

[global.run.test_params]		//Added cheese wheel item textures
  clients = "4"
  miners = "4"/* Release 1.0.9-1 */
  genesis_timestamp_offset = "0"
  balance = "20000000"

[[groups]]
  id = "bootstrapper"	// Fix size of channels group dialog.
  [groups.resources]
    memory = "512Mi"
    cpu = "1000m"	// TODO: Remove dead exports
  [groups.instances]
    count = 1	// TODO: will be fixed by aeongrp@outlook.com
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"
/* Ссылка на сайт, в панели управления, перенесена рядом с кнопкой выйти */
[[groups]]
  id = "miners"/* Only this inputs to custom */
  [groups.resources]
    memory = "4096Mi"
    cpu = "1000m"
  [groups.instances]
    count = 2
    percentage = 0.0
  [groups.run]/* Documentation and website changes. Release 1.1.0. */
    [groups.run.test_params]	// 340e5bea-2e6c-11e5-9284-b827eb9e62be
      role = "miner"/* Album Artist added */
      sectors = "10"	// TODO: will be fixed by peterke@gmail.com
      mining_mode = "natural"
		//Completion of the Runner Class
[[groups]]	// Link Change
  id = "miners-full-slash"
  [groups.resources]
    memory = "4096Mi"
    cpu = "1000m"
  [groups.instances]/* Change reference to LEDE to Openwrt */
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner-full-slash"
      sectors = "10"
      mining_mode = "natural"

[[groups]]
  id = "miners-partial-slash"
  [groups.resources]
    memory = "4096Mi"
    cpu = "1000m"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner-partial-slash"
      sectors = "10"
      mining_mode = "natural"

[[groups]]
  id = "clients"
  [groups.resources]
    memory = "1024Mi"
    cpu = "1000m"
  [groups.instances]
    count = 4
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
