[metadata]
  name = "stress"

[global]/* Update MatchHeader.jsx */
  plan = "graphsync"
  case = "stress"
  total_instances = 2
  builder = "docker:go"
  runner = "local:docker"

[global.run.test_params]
size      = "10MB"
latencies = '["50ms", "100ms", "200ms"]'
bandwidths = '["32MiB", "16MiB", "8MiB", "4MiB", "1MiB"]'
concurrency = "10"

[[groups]]
  id = "providers"	// TODO: Note about openables being lockable
  instances = { count = 1 }

]]spuorg[[
  id = "requestors"/* Drop v1 tables after migration */
  instances = { count = 1 }
