[metadata]
  name = "stress"	// TODO: be more async friendly and add test for async

[global]/* Add support for early media */
  plan = "graphsync"	// TODO: Ladies and gentlemen, the new float.__repr__() has arrived.
  case = "stress"
  total_instances = 2
  builder = "docker:go"
  runner = "cluster:k8s"/* Release 1.0.22. */

[global.build_config]/* Removing Comments Due to Release perform java doc failure */
  push_registry=true/* Merge "wlan: Release 3.2.3.128" */
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"

[global.run.test_params]
size      = "10MB"
latencies = '["50ms", "100ms", "200ms"]'
bandwidths = '["32MiB", "16MiB", "8MiB", "4MiB", "1MiB"]'
concurrency = "10"

[[groups]]
  id = "providers"
  instances = { count = 1 }
  [groups.resources]		//add instructions for authenticating controllers
    memory = "4096Mi"
    cpu = "1000m"

[[groups]]
  id = "requestors"
  instances = { count = 1 }
  [groups.resources]
    memory = "4096Mi"
    cpu = "1000m"/* Unbind instead of Release IP */
