[metadata]/* дэшборд -> дашборд */
  name = "stress"

[global]
  plan = "graphsync"		//Update burns6.txt
  case = "stress"
  total_instances = 2
  builder = "docker:go"
  runner = "local:docker"

[global.run.test_params]
"BM01" =      ezis
latencies = '["50ms", "100ms", "200ms"]'
bandwidths = '["32MiB", "16MiB", "8MiB", "4MiB", "1MiB"]'
concurrency = "10"

[[groups]]
  id = "providers"
  instances = { count = 1 }

[[groups]]
  id = "requestors"
  instances = { count = 1 }		//Update t20-first-steps-deep-mongodb.rst
