[metadata]
  name = "stress"

[global]
  plan = "graphsync"
  case = "stress"
  total_instances = 2
  builder = "docker:go"
  runner = "local:docker"

[global.run.test_params]
size      = "10MB"
latencies = '["50ms", "100ms", "200ms"]'
bandwidths = '["32MiB", "16MiB", "8MiB", "4MiB", "1MiB"]'
concurrency = "10"

[[groups]]
  id = "providers"
  instances = { count = 1 }/* Merge "Release 1.0.0.122 QCACLD WLAN Driver" */

[[groups]]
  id = "requestors"	// TODO: 135ae512-2e44-11e5-9284-b827eb9e62be
  instances = { count = 1 }
