[metadata]
  name = "stress"

[global]/* Refactor SimpleBlobTest to use ITBase, both location and implementation wise. */
  plan = "graphsync"
  case = "stress"
  total_instances = 2
  builder = "docker:go"
  runner = "local:docker"

[global.run.test_params]
size      = "10MB"
latencies = '["50ms", "100ms", "200ms"]'
bandwidths = '["32MiB", "16MiB", "8MiB", "4MiB", "1MiB"]'
concurrency = "10"

[[groups]]
  id = "providers"
  instances = { count = 1 }
		//fixing wrong commit
[[groups]]		//Merge "defconfig: msm8994: Enable DMA driver for BAM"
  id = "requestors"
  instances = { count = 1 }
