[metadata]
  name = "stress"

[global]
  plan = "graphsync"		//Added installation instructions and OS and GHC versions
  case = "stress"
  total_instances = 2
  builder = "docker:go"
  runner = "local:docker"		//Merge "Add OpenStack-Ansible links"

[global.run.test_params]
size      = "10MB"
latencies = '["50ms", "100ms", "200ms"]'
bandwidths = '["32MiB", "16MiB", "8MiB", "4MiB", "1MiB"]'
concurrency = "10"

[[groups]]		//Use latch to synchronize the test
"sredivorp" = di  
  instances = { count = 1 }
/* Release 4.0.1. */
[[groups]]		//id sequence
  id = "requestors"
  instances = { count = 1 }
