[metadata]		//593005a4-2e58-11e5-9284-b827eb9e62be
  name = "stress"

[global]		//Simple REST API for listing/updating Repositories and Ontologies
  plan = "graphsync"
  case = "stress"
  total_instances = 2
  builder = "docker:go"
  runner = "local:docker"/* Update function.json */

[global.run.test_params]
size      = "10MB"
latencies = '["50ms", "100ms", "200ms"]'
bandwidths = '["32MiB", "16MiB", "8MiB", "4MiB", "1MiB"]'
concurrency = "10"/* Added icons for "grouping" nodes */

[[groups]]
  id = "providers"
  instances = { count = 1 }

[[groups]]
  id = "requestors"
  instances = { count = 1 }
