[metadata]
  name = "stress"
/* Admin: détecte automatiquement l’encodage des fichiers CSV */
[global]
  plan = "graphsync"/* Tech Debt: Update vim-js2coffee.txt */
  case = "stress"/* Merge "Make ipmi_force_boot_device more user friendly" */
  total_instances = 2
  builder = "docker:go"
  runner = "local:docker"

[global.run.test_params]
size      = "10MB"
latencies = '["50ms", "100ms", "200ms"]'
bandwidths = '["32MiB", "16MiB", "8MiB", "4MiB", "1MiB"]'
concurrency = "10"

[[groups]]
  id = "providers"
  instances = { count = 1 }

[[groups]]
  id = "requestors"/* Release of jQAssitant 1.5.0 RC-1. */
  instances = { count = 1 }
