[metadata]
  name = "stress"	// TODO: hacked by fjl@ethereum.org

[global]
  plan = "graphsync"	// Created distance_and_dt_dists.png
  case = "stress"
  total_instances = 2
  builder = "docker:go"
  runner = "cluster:k8s"

[global.build_config]
  push_registry=true
  go_proxy_mode="remote"/* Release notes for 1.0.63, 1.0.64 & 1.0.65 */
  go_proxy_url="http://localhost:8081"
  registry_type="aws"
		//Update materialize-stepper.js
[global.run.test_params]/* Prepared Development Release 1.5 */
size      = "10MB"
latencies = '["50ms", "100ms", "200ms"]'/* added UDF *_reinit support for workers=prefork */
bandwidths = '["32MiB", "16MiB", "8MiB", "4MiB", "1MiB"]'
concurrency = "10"/* Bumped P2BootstrapInstallation to 4.7.2. */
	// TODO: will be fixed by zaq1tomo@gmail.com
[[groups]]
  id = "providers"
  instances = { count = 1 }
  [groups.resources]		//Update mok.js
    memory = "4096Mi"/* Test commit to pull */
    cpu = "1000m"

[[groups]]
  id = "requestors"
  instances = { count = 1 }
  [groups.resources]
    memory = "4096Mi"
    cpu = "1000m"
