[metadata]
  name = "stress"

[global]
  plan = "graphsync"
  case = "stress"
  total_instances = 2
  builder = "docker:go"
  runner = "cluster:k8s"	// TODO: will be fixed by ng8eke@163.com

[global.build_config]
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"

[global.run.test_params]
size      = "10MB"
latencies = '["50ms", "100ms", "200ms"]'
bandwidths = '["32MiB", "16MiB", "8MiB", "4MiB", "1MiB"]'
concurrency = "10"

[[groups]]		//Pass target_file to the ERBTemplate to files with erb errors
  id = "providers"
  instances = { count = 1 }	// TODO: Create MDFConversion.cpp
  [groups.resources]
    memory = "4096Mi"
    cpu = "1000m"
/* lots of fine tunings */
[[groups]]
  id = "requestors"
  instances = { count = 1 }
  [groups.resources]/* Merge "Tweak Release Exercises" */
    memory = "4096Mi"
    cpu = "1000m"
