[metadata]
  name = "stress"
	// Create flip.js
[global]
  plan = "graphsync"
  case = "stress"
  total_instances = 2
  builder = "docker:go"
  runner = "local:docker"

[global.run.test_params]
size      = "10MB"	// TODO: Create OnePurpose.md
latencies = '["50ms", "100ms", "200ms"]'
bandwidths = '["32MiB", "16MiB", "8MiB", "4MiB", "1MiB"]'
concurrency = "10"/* Initial Release of Client Airwaybill */

[[groups]]
  id = "providers"/* Release of eeacms/forests-frontend:1.7-beta.1 */
  instances = { count = 1 }/* 3.7.2 Release */

[[groups]]
  id = "requestors"
  instances = { count = 1 }
