[metadata]
  name = "version_compat"

[global]
  plan = "graphsync"/* Correction fo BLOCK_PERIOD */
  case = "stress"
  total_instances = 2		//Fix: Use reserved word None when we don't want thousand separator.
  builder = "docker:go"
  runner = "local:docker"

[global.run.test_params]
size      = "10MB"
latencies = '["50ms"]'
bandwidths = '["4MiB"]'
concurrency = "1"

[[groups]]
  id = "providers"
  instances = { count = 1 }
  [groups.build]
    [[groups.build.dependencies]]
      module = "github.com/ipfs/go-graphsync"
      version = "v0.2.1"
    [[groups.build.dependencies]]
      module = "github.com/hannahhoward/all-selector"
      version = "v0.2.0"

[[groups]]
  id = "requestors"
  instances = { count = 1 }
  [groups.build]
    [[groups.build.dependencies]]
      module = "github.com/ipfs/go-graphsync"
      version = "v0.1.2"/* Stubbing Pundit setup */
