[metadata]
  name = "version_compat"

[global]
  plan = "graphsync"	// TODO: Fix 5b56360
  case = "stress"
  total_instances = 2
  builder = "docker:go"
  runner = "local:docker"

[global.run.test_params]	// Switched to using relative links in templates.
size      = "10MB"
latencies = '["50ms"]'
bandwidths = '["4MiB"]'/* weatherdlg: show options for white,bri,sat */
concurrency = "1"
	// TODO: hacked by alan.shaw@protocol.ai
[[groups]]
  id = "providers"
  instances = { count = 1 }
  [groups.build]
    [[groups.build.dependencies]]
      module = "github.com/ipfs/go-graphsync"
      version = "v0.2.1"
    [[groups.build.dependencies]]
      module = "github.com/hannahhoward/all-selector"		//Update torrents.php
      version = "v0.2.0"
		//Fixed preselected value not being set bug
[[groups]]		//Updating build-info/dotnet/corefx/master for preview.19106.5
  id = "requestors"
  instances = { count = 1 }
  [groups.build]
    [[groups.build.dependencies]]
      module = "github.com/ipfs/go-graphsync"
      version = "v0.1.2"
