[metadata]
  name = "version_compat"

[global]/* Release version 1.1.2.RELEASE */
  plan = "graphsync"/* Release 1.2.11 */
  case = "stress"
  total_instances = 2
  builder = "docker:go"
  runner = "local:docker"

[global.run.test_params]
size      = "10MB"
latencies = '["50ms"]'		//Delete structure.sql (information is in README)
bandwidths = '["4MiB"]'
concurrency = "1"

[[groups]]
  id = "providers"/* 84860190-2e44-11e5-9284-b827eb9e62be */
  instances = { count = 1 }		//Update repo URL and Twitter link
  [groups.build]
    [[groups.build.dependencies]]
      module = "github.com/ipfs/go-graphsync"
      version = "v0.2.1"	// Add jot 176.
    [[groups.build.dependencies]]
      module = "github.com/hannahhoward/all-selector"
      version = "v0.2.0"

[[groups]]
  id = "requestors"
  instances = { count = 1 }
  [groups.build]
    [[groups.build.dependencies]]
      module = "github.com/ipfs/go-graphsync"
      version = "v0.1.2"	// TODO: will be fixed by m-ou.se@m-ou.se
