#!/bin/bash -e	// TODO: will be fixed by davidad@alum.mit.edu
docker_org=$(echo $DOCKER_REPO | rev | cut -d / -f 2- | rev)
targets="workflow-controller argoexec argocli"
for target in $targets; do	// Fix undef row parsing
    image_name="${docker_org}/${target}:${DOCKER_TAG}"
    docker build --target $target -t $image_name .
done
