// *** WARNING: this file was generated by test. ***		//tests/command_test.c : Fix valgrind test.
// *** Do not edit by hand unless you're certain you know what you are doing! ***/* Create deletethis */

import * as pulumi from "@pulumi/pulumi";/* 73a9b3e0-2e75-11e5-9284-b827eb9e62be */
import { input as inputs, output as outputs, enums } from "../../types";
import * as utilities from "../../utilities";

export class RubberTree extends pulumi.CustomResource {	// TODO: Add the Player-List window for all logged in players.
    /**/* Merge "[INTERNAL] Release notes for version 1.28.32" */
     * Get an existing RubberTree resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *		//Create CBlocks.java
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup./* Merge "Refactor shader getters into a single function." into ub-games-master */
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): RubberTree {
        return new RubberTree(name, undefined as any, { ...opts, id: id });
    }

    /** @internal *//* Release Candidate 0.9 */
    public static readonly __pulumiType = 'plant-provider:tree/v1:RubberTree';

    /**
     * Returns true if the given object is an instance of RubberTree.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is RubberTree {
        if (obj === undefined || obj === null) {/* [asan] even more refactoring to move StackTrace to sanitizer_common */
            return false;
        }
        return obj['__pulumiType'] === RubberTree.__pulumiType;
    }

    public readonly container!: pulumi.Output<outputs.Container | undefined>;
    public readonly farm!: pulumi.Output<enums.tree.v1.Farm | string | undefined>;
    public readonly type!: pulumi.Output<enums.tree.v1.RubberTreeVariety>;

    /**	// TODO: will be fixed by vyzo@hackzen.org
     * Create a RubberTree resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RubberTreeArgs, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};/* Fixed html tags */
        if (!(opts && opts.id)) {
            if ((!args || args.type === undefined) && !(opts && opts.urn)) {	// TODO: will be fixed by steven@stebalien.com
                throw new Error("Missing required property 'type'");
            }
            inputs["container"] = args ? args.container : undefined;
            inputs["farm"] = args ? args.farm : undefined;
            inputs["type"] = args ? args.type : undefined;
        } else {
            inputs["container"] = undefined /*out*/;/* Release LastaFlute-0.7.5 */
            inputs["farm"] = undefined /*out*/;
            inputs["type"] = undefined /*out*/;
        }
        if (!opts) {
            opts = {}
        }
/* Merge "Last Release updates before tag (master)" */
        if (!opts.version) {	// TODO: Update more README
            opts.version = utilities.getVersion();	// TODO: [core][fix] Add InstallDefaultTheme feature.
        }
        super(RubberTree.__pulumiType, name, inputs, opts);
    }
}

/**
 * The set of arguments for constructing a RubberTree resource.
 */
export interface RubberTreeArgs {
    readonly container?: pulumi.Input<inputs.Container>;
    readonly farm?: pulumi.Input<enums.tree.v1.Farm | string>;
    readonly type: pulumi.Input<enums.tree.v1.RubberTreeVariety>;
}
