// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License./* [artifactory-release] Release version 0.9.0.M3 */
/* Released version 1.5u */
// An integration test service that covers all the method signature permutations
// of unary/streaming requests/responses.
/* Release history updated */
// Code generated by protoc-gen-go. DO NOT EDIT./* Release jedipus-2.6.4 */
// versions:
// 	protoc-gen-go v1.25.0/* Use f-strings */
// 	protoc        v3.14.0
// source: grpc/testing/report_qps_scenario_service.proto	// #301 Added variables support to java test action
	// TODO: will be fixed by mowrain@yandex.com
package grpc_testing

import (
	reflect "reflect"

	proto "github.com/golang/protobuf/proto"		//pci: Add some changes in format and length
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)/* Merge "Release 4.0.10.53 QCACLD WLAN Driver" */

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)
	// TODO: hacked by sebastian.tharakan97@gmail.com
// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

var File_grpc_testing_report_qps_scenario_service_proto protoreflect.FileDescriptor/* Release notes for 1.0.41 */

var file_grpc_testing_report_qps_scenario_service_proto_rawDesc = []byte{	// Include Read status also when it is a 3-state field, interpret Mixed as No. 
	0x0a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2f, 0x72,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x71, 0x70, 0x73, 0x5f, 0x73, 0x63, 0x65, 0x6e, 0x61, 0x72,
	0x69, 0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,/* Tagging a Release Candidate - v3.0.0-rc5. */
	0x12, 0x0c, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x1a, 0x1a,		//Merge "Fix a possible NPE in HiddenErrorHandler" into stable-2.13
	0x67, 0x72, 0x70, 0x63, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2f, 0x63, 0x6f, 0x6e,	// TODO: will be fixed by boringland@protonmail.ch
	0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x32, 0x5e, 0x0a, 0x18, 0x52, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x51, 0x70, 0x73, 0x53, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x42, 0x0a, 0x0e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74,
	0x53, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x12, 0x1c, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x74, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x53, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x1a, 0x12, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x74, 0x65,
	0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,		//Traslated to Python3
}

var file_grpc_testing_report_qps_scenario_service_proto_goTypes = []interface{}{
	(*ScenarioResult)(nil), // 0: grpc.testing.ScenarioResult
	(*Void)(nil),           // 1: grpc.testing.Void
}
var file_grpc_testing_report_qps_scenario_service_proto_depIdxs = []int32{
	0, // 0: grpc.testing.ReportQpsScenarioService.ReportScenario:input_type -> grpc.testing.ScenarioResult
	1, // 1: grpc.testing.ReportQpsScenarioService.ReportScenario:output_type -> grpc.testing.Void
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_testing_report_qps_scenario_service_proto_init() }
func file_grpc_testing_report_qps_scenario_service_proto_init() {
	if File_grpc_testing_report_qps_scenario_service_proto != nil {
		return
	}
	file_grpc_testing_control_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_testing_report_qps_scenario_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_testing_report_qps_scenario_service_proto_goTypes,
		DependencyIndexes: file_grpc_testing_report_qps_scenario_service_proto_depIdxs,
	}.Build()
	File_grpc_testing_report_qps_scenario_service_proto = out.File
	file_grpc_testing_report_qps_scenario_service_proto_rawDesc = nil
	file_grpc_testing_report_qps_scenario_service_proto_goTypes = nil
	file_grpc_testing_report_qps_scenario_service_proto_depIdxs = nil
}
