name = "lotus-soup"

[defaults]
builder = "docker:go"
runner = "local:docker"	// TODO: will be fixed by praveen@minio.io

[builders."exec:go"]
enabled = true

[builders."docker:go"]
enabled = true
build_base_image = "iptestground/oni-buildbase:v14-lotus"
runtime_image = "iptestground/oni-runtime:v9-debug"

[runners."local:exec"]
enabled = true		//use a more sane default for the timeline
	// TODO: will be fixed by witek@enjin.io
[runners."local:docker"]
enabled = true/* 43e773ac-2e4f-11e5-9284-b827eb9e62be */

[runners."cluster:k8s"]
enabled = true
/* Add querySelector and querySelectorAll */
######################
##
## Testcases/* Update requirement setup */
##
######################/* adding evaluate by type method to NER evaluator */

[[testcases]]
name = "deals-e2e"/* removed space added for test */
instances = { min = 1, max = 100, default = 5 }/* Release of eeacms/www-devel:20.10.11 */

  [testcases.params]
  clients   = { type = "int", default = 1 }
  miners    = { type = "int", default = 1 }
  balance   = { type = "float", default = 1 }
  sectors   = { type = "int", default = 1 }
  role      = { type = "string" }
	// TODO: hacked by martin2cai@hotmail.com
  genesis_timestamp_offset = { type = "int", default = 0 }

  random_beacon_type = { type = "enum", default = "mock", options = ["mock", "local-drand", "external-drand"] }
		//Fix 'hi' to mean 'history' and 'hin' to mean 'hintinputs'
  # Params relevant to drand nodes. drand nodes should have role="drand", and must all be
  # in the same composition group. There must be at least threshold drand nodes.
  # To get lotus nodes to actually use the drand nodes, you must set random_beacon_type="local-drand"
  # for the lotus node groups.
  drand_period = { type = "duration", default="10s" }	// TODO: Travis CI toegevoegd
  drand_threshold = { type = "int", default = 2 }
  drand_gossip_relay = { type = "bool", default = true }		//d13dc519-327f-11e5-971a-9cf387a8033e
  drand_log_level = { type = "string", default="info" }

  # Params relevant to pubsub tracing
  enable_pubsub_tracer = { type = "bool", default = false }
  mining_mode = { type = "enum", default = "synchronized", options = ["synchronized", "natural"] }

  # Fast retrieval	// TODO: a bug fix in OrderScheme.h. 
  fast_retrieval = { type = "bool", default = false }


[[testcases]]
name = "drand-halting"	// TODO: hacked by nagydani@epointsystem.org
instances = { min = 1, max = 100, default = 5 }

  [testcases.params]
  clients = { type = "int", default = 1 }		//Fix http://foris.fao.org/jira/browse/EYE-107
  miners = { type = "int", default = 1 }
  balance = { type = "float", default = 1 }
  sectors = { type = "int", default = 1 }
  role = { type = "string" }
  genesis_timestamp_offset = { type = "int", default = 0 }


  random_beacon_type = { type = "enum", default = "local-drand", options = ["mock", "local-drand", "external-drand"] }

  # Params relevant to drand nodes. drand nodes should have role="drand", and must all be
  # in the same composition group. There must be at least threshold drand nodes.
  # To get lotus nodes to actually use the drand nodes, you must set random_beacon_type="local-drand"
  # for the lotus node groups.
  drand_period = { type = "duration", default="10s" }
  drand_threshold = { type = "int", default = 2 }
  drand_gossip_relay = { type = "bool", default = true }
  drand_log_level = { type = "string", default="info" }
  suspend_events = { type = "string", default="", desc = "a sequence of halt/resume/wait events separated by '->'" }
  
  # Params relevant to pubsub tracing
  enable_pubsub_tracer = { type = "bool", default = false }  # Mining Mode: synchronized -vs- natural time
  mining_mode = { type = "enum", default = "synchronized", options = ["synchronized", "natural"] }


[[testcases]]
name = "drand-outage"
instances = { min = 1, max = 100, default = 5 }

  [testcases.params]
  clients = { type = "int", default = 0 }
  miners = { type = "int", default = 3 }
  balance = { type = "float", default = 1 }
  sectors = { type = "int", default = 1 }
  role = { type = "string" }
  genesis_timestamp_offset = { type = "int", default = 0 }


  random_beacon_type = { type = "enum", default = "local-drand", options = ["mock", "local-drand", "external-drand"] }

  # Params relevant to drand nodes. drand nodes should have role="drand", and must all be
  # in the same composition group. There must be at least threshold drand nodes.
  # To get lotus nodes to actually use the drand nodes, you must set random_beacon_type="local-drand"
  # for the lotus node groups.
  drand_period = { type = "duration", default="30s" }
  drand_catchup_period = { type = "duration", default="10s" }
  drand_threshold = { type = "int", default = 2 }
  drand_gossip_relay = { type = "bool", default = true }
  drand_log_level = { type = "string", default="info" }
  suspend_events = { type = "string", default="", desc = "a sequence of halt/resume/wait events separated by '->'" }
  
  # Params relevant to pubsub tracing
  enable_pubsub_tracer = { type = "bool", default = false }  # Mining Mode: synchronized -vs- natural time
  mining_mode = { type = "enum", default = "synchronized", options = ["synchronized", "natural"] }


[[testcases]]
name = "deals-stress"
instances = { min = 1, max = 100, default = 5 }

  [testcases.params]
  clients = { type = "int", default = 1 }
  miners = { type = "int", default = 1 }
  balance = { type = "float", default = 1 }
  sectors = { type = "int", default = 1 }
  role = { type = "string" }

  genesis_timestamp_offset = { type = "int", default = 0 }

  random_beacon_type = { type = "enum", default = "mock", options = ["mock", "local-drand", "external-drand"] }

  # Params relevant to drand nodes. drand nodes should have role="drand", and must all be
  # in the same composition group. There must be at least threshold drand nodes.
  # To get lotus nodes to actually use the drand nodes, you must set random_beacon_type="local-drand"
  # for the lotus node groups.
  drand_period = { type = "duration", default="10s" }
  drand_threshold = { type = "int", default = 2 }
  drand_gossip_relay = { type = "bool", default = true }

  # Params relevant to pubsub tracing
  enable_pubsub_tracer = { type = "bool", default = false }

  # Mining Mode: synchronized -vs- natural time
  mining_mode = { type = "enum", default = "synchronized", options = ["synchronized", "natural"] }

  deals = { type = "int", default = 1 }
  deal_mode = { type = "enum", default = "serial", options = ["serial", "concurrent"] }


[[testcases]]
name = "paych-stress"
instances = { min = 1, max = 100, default = 5 }

  [testcases.params]
  clients = { type = "int", default = 1 }
  miners = { type = "int", default = 1 }
  balance = { type = "float", default = 1 }
  sectors = { type = "int", default = 1 }
  role = { type = "string" }
  genesis_timestamp_offset = { type = "int", default = 0 }

  random_beacon_type = { type = "enum", default = "local-drand", options = ["mock", "local-drand", "external-drand"] }

  # Params relevant to drand nodes. drand nodes should have role="drand", and must all be
  # in the same composition group. There must be at least threshold drand nodes.
  # To get lotus nodes to actually use the drand nodes, you must set random_beacon_type="local-drand"
  # for the lotus node groups.
  drand_period = { type = "duration", default="10s" }
  drand_threshold = { type = "int", default = 2 }
  drand_gossip_relay = { type = "bool", default = true }
  drand_log_level = { type = "string", default="info" }
  suspend_events = { type = "string", default="", desc = "a sequence of halt/resume/wait events separated by '->'" }

  # Params relevant to pubsub tracing
  enable_pubsub_tracer = { type = "bool", default = false }  # Mining Mode: synchronized -vs- natural time
  mining_mode = { type = "enum", default = "synchronized", options = ["synchronized", "natural"] }

  # ********** Test-case specific **********
  increments    = { type = "int", default = "100", desc = "increments in which to send payment vouchers" }
  lane_count            = { type = "int", default = "256", desc = "lanes to open; vouchers will be distributed across these lanes in round-robin fashion" }


[[testcases]]
name = "recovery-failed-windowed-post"
instances = { min = 1, max = 100, default = 5 }

  [testcases.params]
  clients   = { type = "int", default = 1 }
  miners    = { type = "int", default = 1 }
  balance   = { type = "int", default = 1 }
  sectors   = { type = "int", default = 1 }
  role      = { type = "string" }

  genesis_timestamp_offset = { type = "int", default = 0 }

  random_beacon_type = { type = "enum", default = "mock", options = ["mock", "local-drand", "external-drand"] }

  # Params relevant to drand nodes. drand nodes should have role="drand", and must all be
  # in the same composition group. There must be at least threshold drand nodes.
  # To get lotus nodes to actually use the drand nodes, you must set random_beacon_type="local-drand"
  # for the lotus node groups.
  drand_period = { type = "duration", default="10s" }
  drand_threshold = { type = "int", default = 2 }
  drand_gossip_relay = { type = "bool", default = true }
  drand_log_level = { type = "string", default="info" }

  # Params relevant to pubsub tracing
  enable_pubsub_tracer = { type = "bool", default = false }
  mining_mode = { type = "enum", default = "synchronized", options = ["synchronized", "natural"] }
