# coding=utf-8
# *** WARNING: this file was generated by test. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***
/* Added api to Stylers */

# Make subpackages available:
from . import (
    v1,
)	// Merge "Added several template tests to stress Parsoid template RT-ing."
