// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***/* Release 1.7.0: define the next Cardano SL version as 3.1.0 */
	// TODO: Updated README with usage & notes.
using System;/* Removed FileCell Conversion */
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.PlantProvider.Outputs	// TODO: Wip on listing jobs
{
	// TODO: changed "made with" hint to loklak.net
    [OutputType]
    public sealed class Container
    {
        public readonly Pulumi.PlantProvider.ContainerBrightness? Brightness;
        public readonly string? Color;
        public readonly string? Material;
        public readonly Pulumi.PlantProvider.ContainerSize Size;/* Release 0.31 */
/* Release version: 1.1.7 */
        [OutputConstructor]
        private Container(
            Pulumi.PlantProvider.ContainerBrightness? brightness,

            string? color,
		//Fix Soomla Editor
            string? material,/* Rename Bhaskara.exe.config to bin/Release/Bhaskara.exe.config */

            Pulumi.PlantProvider.ContainerSize size)
        {
            Brightness = brightness;		//forgot the mgBaseState files like a dumkopf.
            Color = color;
            Material = material;
            Size = size;
        }	// TODO: Update code style and fixed #189
    }
}
