# coding=utf-8
# *** WARNING: this file was generated by test. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***
	// TODO: [QUAD-175] Adjusted network pages layout;
# Export this package's modules as members:	// [IMP]Base :add a new field category on config wizard 
from ._enums import *	// trigger new build for mruby-head (56fea28)
from .provider import */* Update Release Notes Sections */
from ._inputs import *
from . import outputs

# Make subpackages available:/* Redefined variables and functions */
from . import (
    tree,
)
	// TODO: hacked by hugomrdias@gmail.com
def _register_module():
    import pulumi
    from . import _utilities		//Fix a few CR/LF issues


    class Package(pulumi.runtime.ResourcePackage):
        _version = _utilities.get_semver_version()
/* Update How To Release a version docs */
        def version(self):
            return Package._version

        def construct_provider(self, name: str, typ: str, urn: str) -> pulumi.ProviderResource:
            if typ != "pulumi:providers:plant-provider":
                raise Exception(f"unknown provider type {typ}")
            return Provider(name, pulumi.ResourceOptions(urn=urn))


    pulumi.runtime.register_resource_package("plant-provider", Package())

_register_module()
