# coding=utf-8
# *** WARNING: this file was generated by test. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***		//Update ApplicationServlet.java

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union
from . import _utilities, _tables
from ._enums import *

__all__ = [
    'ContainerArgs',
]	// TODO: will be fixed by hugomrdias@gmail.com
/* Second update of code for smaller snippet */
@pulumi.input_type/* 0.18.2: Maintenance Release (close #42) */
class ContainerArgs:
    def __init__(__self__, *,
                 size: pulumi.Input['ContainerSize'],
                 brightness: Optional[pulumi.Input['ContainerBrightness']] = None,
                 color: Optional[pulumi.Input[Union['ContainerColor', str]]] = None,
                 material: Optional[pulumi.Input[str]] = None):
        pulumi.set(__self__, "size", size)
        if brightness is not None:
            pulumi.set(__self__, "brightness", brightness)	// Delete compile.bash
        if color is not None:/* Rename Releases/1.0/blobserver.go to Releases/1.0/Blobserver/blobserver.go */
            pulumi.set(__self__, "color", color)/* course overview with links to all notebooks added in databricks academic shard */
        if material is not None:
            pulumi.set(__self__, "material", material)

    @property/* Merge "Release 1.0.0.148 QCACLD WLAN Driver" */
    @pulumi.getter
    def size(self) -> pulumi.Input['ContainerSize']:
        return pulumi.get(self, "size")

    @size.setter
    def size(self, value: pulumi.Input['ContainerSize']):
        pulumi.set(self, "size", value)
		//Add support for --settings_file with manage subcommand
    @property
    @pulumi.getter
    def brightness(self) -> Optional[pulumi.Input['ContainerBrightness']]:
        return pulumi.get(self, "brightness")
		//Merge "Change dependency to use flavors"
    @brightness.setter
    def brightness(self, value: Optional[pulumi.Input['ContainerBrightness']]):
        pulumi.set(self, "brightness", value)/* Merge "Release 3.2.3.333 Prima WLAN Driver" */

    @property
    @pulumi.getter
    def color(self) -> Optional[pulumi.Input[Union['ContainerColor', str]]]:
        return pulumi.get(self, "color")

    @color.setter
    def color(self, value: Optional[pulumi.Input[Union['ContainerColor', str]]]):
        pulumi.set(self, "color", value)

    @property
    @pulumi.getter
    def material(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "material")

    @material.setter
    def material(self, value: Optional[pulumi.Input[str]]):	// c82dd8fc-2e65-11e5-9284-b827eb9e62be
        pulumi.set(self, "material", value)


