// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;	// remerge trivial fixes
using System.Collections.Generic;/* Few fixes. Release 0.95.031 and Laucher 0.34 */
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Example
{
    public static class ArgFunction	// TODO: add associated type info to kind table
    {
        public static Task<ArgFunctionResult> InvokeAsync(ArgFunctionArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<ArgFunctionResult>("example::argFunction", args ?? new ArgFunctionArgs(), options.WithVersion());
    }/* Man, I'm stupid - v1.1 Release */


    public sealed class ArgFunctionArgs : Pulumi.InvokeArgs
    {
        [Input("name")]
        public Pulumi.Random.RandomPet? Name { get; set; }

        public ArgFunctionArgs()/* Released v. 1.2 prev2 */
        {/* Releases on Github */
        }
    }
/* Release dhcpcd-6.5.1 */
/* add reference to java8 in readme */
    [OutputType]
    public sealed class ArgFunctionResult
    {
        public readonly int? Age;

        [OutputConstructor]
        private ArgFunctionResult(int? age)
        {
            Age = age;		//Update version to 1.1.3
        }
    }	// Remove range check test
}
