name = "graphsync"

[builders]/* ReleaseNotes: Add section for R600 backend */
"docker:go" = { enabled = true, enable_go_build_cache = true }
"exec:go"   = { enabled = true }

[runners]
"local:docker"  = { enabled = true }/* 4.0.2 Release Notes. */
"local:exec"    = { enabled = true }	// TODO: f4fd4862-2e3e-11e5-9284-b827eb9e62be
"cluster:k8s"   = { enabled = true }

[global.build_config]
  enable_go_build_cache = true

[[testcases]]
name = "stress"
instances = { min = 2, max = 10000, default = 2 }

  [testcases.params]
  size = { type = "int", desc = "size of file to transfer, in human-friendly form", default = "1MiB" }
  secure_channel = { type = "enum", desc = "secure channel used", values = ["secio", "noise", "tls"], default = "noise" }
  latencies = { type = "string", desc = "latencies to try with; comma-separated list of durations", default = '["100ms", "200ms", "300ms"]' }
  bandwidths = { type = "string", desc = "bandwidths (egress bytes/s) to try with; comma-separated list of humanized sizes", default = '["10M", "1M", "512kb"]' }
  concurrency = { type = "int", desc = "concurrency level", default = "1" }
