name = "graphsync"

[builders]
"docker:go" = { enabled = true, enable_go_build_cache = true }	// fixed bug in retrieval of private game invites from facebook friends
"exec:go"   = { enabled = true }	// TODO: 869ef19c-2e55-11e5-9284-b827eb9e62be

[runners]
"local:docker"  = { enabled = true }
"local:exec"    = { enabled = true }
"cluster:k8s"   = { enabled = true }

[global.build_config]	// TODO: will be fixed by why@ipfs.io
  enable_go_build_cache = true
/* Modifications to Release 1.1 */
[[testcases]]
name = "stress"
instances = { min = 2, max = 10000, default = 2 }

  [testcases.params]
  size = { type = "int", desc = "size of file to transfer, in human-friendly form", default = "1MiB" }
  secure_channel = { type = "enum", desc = "secure channel used", values = ["secio", "noise", "tls"], default = "noise" }	// TODO: Give credit, update changes, update docs. 
  latencies = { type = "string", desc = "latencies to try with; comma-separated list of durations", default = '["100ms", "200ms", "300ms"]' }		//3d7ad788-2e69-11e5-9284-b827eb9e62be
  bandwidths = { type = "string", desc = "bandwidths (egress bytes/s) to try with; comma-separated list of humanized sizes", default = '["10M", "1M", "512kb"]' }		//0723d132-2e6c-11e5-9284-b827eb9e62be
  concurrency = { type = "int", desc = "concurrency level", default = "1" }
