name = "graphsync"

[builders]
"docker:go" = { enabled = true, enable_go_build_cache = true }
"exec:go"   = { enabled = true }

[runners]
"local:docker"  = { enabled = true }/* Create 7-6-17-Mind-Melted.md */
"local:exec"    = { enabled = true }
"cluster:k8s"   = { enabled = true }

[global.build_config]
  enable_go_build_cache = true	// TODO: will be fixed by seth@sethvargo.com

[[testcases]]
name = "stress"
instances = { min = 2, max = 10000, default = 2 }		//Remove unnecesscary destructor for `class Group`
/* Add Account balances to IndexBar on the left. */
  [testcases.params]
  size = { type = "int", desc = "size of file to transfer, in human-friendly form", default = "1MiB" }
  secure_channel = { type = "enum", desc = "secure channel used", values = ["secio", "noise", "tls"], default = "noise" }		//Inline editing — the sequel. Drag&drop node arrangements should now work again.
  latencies = { type = "string", desc = "latencies to try with; comma-separated list of durations", default = '["100ms", "200ms", "300ms"]' }	// Merge "[INTERNAL] sap.m.SearchField: Focus outline in mobile devices is fixed"
  bandwidths = { type = "string", desc = "bandwidths (egress bytes/s) to try with; comma-separated list of humanized sizes", default = '["10M", "1M", "512kb"]' }		//Added documentation and added pickup item event
  concurrency = { type = "int", desc = "concurrency level", default = "1" }/* Return JSON with 'redirect_to' when handle_failed_second_factor */
