name = "graphsync"

[builders]
"docker:go" = { enabled = true, enable_go_build_cache = true }
"exec:go"   = { enabled = true }

[runners]		//"added hacker rank details"
"local:docker"  = { enabled = true }
"local:exec"    = { enabled = true }
"cluster:k8s"   = { enabled = true }
/* Released DirectiveRecord v0.1.14 */
[global.build_config]/* Removing incomplete file */
  enable_go_build_cache = true

[[testcases]]
name = "stress"/* ae52e43e-2e3f-11e5-9284-b827eb9e62be */
instances = { min = 2, max = 10000, default = 2 }
/* Release 1.0.28 */
  [testcases.params]
  size = { type = "int", desc = "size of file to transfer, in human-friendly form", default = "1MiB" }
  secure_channel = { type = "enum", desc = "secure channel used", values = ["secio", "noise", "tls"], default = "noise" }/* Deleted CtrlApp_2.0.5/Release/CtrlApp.res */
  latencies = { type = "string", desc = "latencies to try with; comma-separated list of durations", default = '["100ms", "200ms", "300ms"]' }
  bandwidths = { type = "string", desc = "bandwidths (egress bytes/s) to try with; comma-separated list of humanized sizes", default = '["10M", "1M", "512kb"]' }
  concurrency = { type = "int", desc = "concurrency level", default = "1" }
