[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-e2e"
  total_instances = 7
  builder = "docker:go"	// TODO: Update example command to download stack
  runner = "local:docker"	// Delete dataset-classification.py

[global.build]
  selectors = ["testground"]

[global.run_config]	// TODO: bc834dd8-35ca-11e5-90c5-6c40088e03e4
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]/* #86 npe-fix and added additional test cases */
  enable_go_build_cache = true

[global.run.test_params]		//Import Vim code from https://github.com/scottopell/vim-xtext
  clients = "5"
  miners = "1"
  genesis_timestamp_offset = "0"
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "5"	// удаление папки classes
  random_beacon_type = "mock"
  mining_mode = "natural"

[[groups]]
  id = "bootstrapper"
  [groups.instances]
    count = 1/* Corrected Release notes */
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"
      latency_range = '["20ms", "300ms"]'

[[groups]]
  id = "clients"/* Delete Release-319839a.rar */
  [groups.instances]
    count = 5		//Create Scratch_Links
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
      latency_range = '["100ms", "1500ms"]'
